### ISSUE TITLE
How to enable Debug for integ-test ES server in elastic search

### ISSUE THREAD

**Issue by FreCap** [opensearch-project/sql#102]
Running normal tests (without ES RestIntegTestTask) in intellij is very easy. We just import the project and run it it the Debug.

However I cannot find a way to run the underlying ES search server in debug mode. 
I tried to add `-Dcluster.debug -Dtest.debug`, but it doesn't seem opening any port and the test will just run without stopping at breakpoints.

I tried to look at the code of the RestIntegTestTask gradle task (https://github.com/search?q=RestIntegTestTask&type=code), but not much insight from it.

Any advice?

**Comment by FreCap** [comment]
Is the only way running the tests against a separately deployed ES server?

I tried to:
- `build/testclusters/integTest-0/config/jvm.options` but it is replaced at every deployement
- add -Dtests.jvm.argline=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005 (https://github.com/elastic/elasticsearch/blob/7.10/buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java#L787) but I couldn't get anything to actually be appended.

@dai-chen do you have any quick hint that could save me?

**Comment by FreCap** [comment]
For future reference, I found a way to make it work

Adding `-Dtests.jvm.argline=-agentlib:jdwp=transport=dt_socket,server=n,address=192.168.4.64:5021,suspend=y` to VM options in the intellij Debug configuration

Important, I used `server=n` because otherwise you need to re-attach the debugger to every ES process (keystore/plugin install, es server etc..). In this way instead you just start the debugger in LISTEN mode and it will automatically re-attach.

![image](https://user-images.githubusercontent.com/1690009/120693117-9cc0d400-c476-11eb-8f20-1f4adce579d1.png)

**Comment by dblock** [comment]
This is a good opportunity to extract a TESTING.md document similar to https://github.com/opensearch-project/OpenSearch/blob/main/TESTING.md

**Comment by dai-chen** [comment]
This PR may fixed the issue. Feel free to reopen if you still face any problem. Thanks!
