### ISSUE TITLE
[SQL] change catalog references to datasource.

### ISSUE THREAD

**Issue by vamsi-amazon** [opensearch-project/sql#1028]
**Is your feature request related to a problem?**
We are going ahead with `datasource` name instead of catalog. The ask from this issue is to rename all the references of catalog to datasource.

**What solution would you like?**

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by Yury-Fridlyand** [comment]
Why not `schema` to comply with other DBs?

**Comment by vamsi-amazon** [comment]
schema represents group of tables under a datasource. 

datasource --> schema --> table is the heirarchy.

In order to not conflict with this project: https://github.com/opensearch-project/opensearch-catalog/blob/main/docs/catalog-rfc.md

we are changing catalog to datasource.

**Comment by Yury-Fridlyand** [comment]
Thank you for clarifying details!
