### ISSUE TITLE
[BUG] Highlight.js used is EOL

### ISSUE THREAD

**Issue by stockholmux** [opensearch-project/sql#103]
**Describe the bug**
A EOL warning is displayed 

**To Reproduce**
1. Open Query Workbench
2. Click "Explain"
3. View the developer console in the browser and see the message `"Version 9 of Highlight.js has reached EOL and is no longer supported. Please upgrade or ask whatever dependency you are using to upgrade. https://github.com/highlightjs/highlight.js/issues/2877"`

**Expected behavior**
No EOL messages

**Plugins**
All OpenSearch Plugins

**Host/Environment (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Version [e.g. 22] Chrome Version 90.0.4430.212 (Official Build) (x86_64)
 (OpenSearch 1.0-RC1)

**Comment by chloe-zh** [comment]
Hi Kyle @stockholmux  thanks for reporting this issue, will investigate it and make a fix.

**Comment by dai-chen** [comment]
I tested in playground and didn't see the warning message any more. Feel free to reopen as needed. Thanks!
