### ISSUE TITLE
[FEATURE] CONCAT on more than two strings

### ISSUE THREAD

**Issue by acarbonetto** [opensearch-project/sql#1053]
**Is your feature request related to a problem?**
```
curl --location --request POST 'http://localhost:9200/_plugins/_sql' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--data-raw '{
    "query": "SELECT concat(\"hello \", \"world\", \"!\") FROM calcs"
}'
```
returns:
```
{
  "error": {
    "reason": "Invalid SQL query",
    "details": "concat function expected {[STRING,STRING]}, but get [STRING,STRING,STRING]",
    "type": "ExpressionEvaluationException"
  },
  "status": 400
}
```

**What solution would you like?**
Expect the concatenated result:  `hello world!`

**What alternatives have you considered?**
Nested queries do work, such as: 
```
{
    "query": "SELECT concat(concat(\"abc\", \"def\"), \"ghi\");"
}
```

returns: 
```
"abcdefghi"
```

**Do you have any additional context?**
n/a

**Comment by dai-chen** [comment]
This may need varargs support or array type which are missing now.

**Comment by Yury-Fridlyand** [comment]
At least we can add `concat` signatures which accept up to 5-8 args and update doc. A user who wants more can use nested call: `concat(concat(1, 2, 3, 4), 5, 6, 7, 8)`

**Comment by margarit-h** [comment]
PR: https://github.com/opensearch-project/sql/pull/1279
