### ISSUE TITLE
[FEATURE] CBRT scalar function in new engine

### ISSUE THREAD

**Issue by acarbonetto** [opensearch-project/sql#1054]
**Is your feature request related to a problem?**
The following statement fails because `CBRT` is not implemented in the new v2 engine

```
{
    "query": "SELECT CBRT(value);"
}
```
error: 
```
{
  "error": {
    "reason": "Invalid SQL query",
    "details": "Cannot invoke \"com.alibaba.druid.sql.ast.statement.SQLTableSource.getAlias()\" because the return value of \"com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlSelectQueryBlock.getFrom()\" is null",
    "type": "NullPointerException"
  },
  "status": 400
}
```

**What solution would you like?**
Something like: https://www.w3resource.com/PostgreSQL/cbrt-function.php

**What alternatives have you considered?**
```
{
    "query": "SELECT CBRT(value) FROM bigint;"
}
```
does work, but this is using the legacy engine for SQL

**Do you have any additional context?**
n/a

**Comment by Yury-Fridlyand** [comment]
WIP: https://github.com/Bit-Quill/opensearch-project-sql/pull/166

**Comment by margarit-h** [comment]
PR: https://github.com/opensearch-project/sql/pull/1081

**Comment by margarit-h** [comment]
PR for adding CBRT() to the PPL: https://github.com/opensearch-project/sql/pull/1097
