### ISSUE TITLE
Use spotless stylecheck in sql project

### ISSUE THREAD

**Issue by penghuo** [opensearch-project/sql#1101]
1. Use [spotless stylecheck](https://github.com/diffplug/spotless/tree/main/plugin-gradle). Spotless checkstyle plugin has the `spotlessApply` task which could automatically format code.
2. Use google code format.

**Comment by penghuo** [comment]
because enforce stylecheck will change too many files, we should find proper time to apply this change. example change. https://github.com/penghuo/os-sql/commit/404265a03670d3d2c071a09e3511d2ec14109e66

**Comment by MitchellGale** [comment]
Note: all sections listed below do not have `*.java` files contained, but still will be added as part of some PR.


**Google Java Format applications and respective PR[s]:**
- [ ] .github
- [ ] .gradle
- [ ] .idea
- [ ] benchmarks
- [ ] build
- [ ] build-tools
- [ ] buildSrc
- [ ] common
- [ ] config
- [ ] core 
https://github.com/opensearch-project/sql/pull/1930 
https://github.com/opensearch-project/sql/pull/1931 
https://github.com/opensearch-project/sql/pull/1932 
https://github.com/opensearch-project/sql/pull/1933
- [ ] datasources
- [ ] docs
- [ ] doctest
- [ ] integ-test
- [ ] legacy
- [ ] opensearch
- [ ] plugin [opensearch-sql-plugin]
- [ ] ppl
- [ ] prometheus
- [ ] protocol
- [ ] release-notes
- [ ] scripts
- [ ] spark
- [ ] spark-sql-application
- [ ] sql
- [ ] entire project

**Comment by MitchellGale** [comment]
Spotless does not format well on `antlr` files. #2017 adds some of the spotless antlr changes that make improvements for the project, but leaves some changes out.
