### ISSUE TITLE
[FEATURE] Support for position in the v2 engine

### ISSUE THREAD

**Issue by acarbonetto** [opensearch-project/sql#1106]
**Is your feature request related to a problem?**
The `POSITION` function is available in the legacy engine, but fails for queries that require the V2 SQL parser or PPL parser. `LOCATE` is already available. 

Example:
```
SELECT POSITION("SS" IN "ISSUE");
```

**What solution would you like?**
`POSITION` is already supported in the legacy engine, and so is `LOCATE`.  Both have similar functionality, and should be both available in the V2 engine. 

**What alternatives have you considered?**
See above

**Do you have any additional context?**
N/A

**Comment by margarit-h** [comment]
Internal WIP PR: https://github.com/Bit-Quill/opensearch-project-sql/pull/177

**Comment by margarit-h** [comment]
PR for SQL support: https://github.com/opensearch-project/sql/pull/1121

**Comment by margarit-h** [comment]
Internal PR for PPL: https://github.com/Bit-Quill/opensearch-project-sql/pull/179

**Comment by margarit-h** [comment]
PR for PPL support: https://github.com/opensearch-project/sql/pull/1147
