### ISSUE TITLE
[BUG] Names don't adhere to plugin naming convention

### ISSUE THREAD

**Issue by mnkugler** [opensearch-project/sql#1122]
**What is the bug?**
As per https://github.com/opensearch-project/opensearch-plugins/blob/main/CONVENTIONS.md#opensearch-plugins, the folder name needs to adhere to the naming convention

**What is the expected behavior?**
[Folder needs to Include full plugin name in kebab case, e.g., plugins/opensearch-sql](https://github.com/opensearch-project/opensearch-plugins/blob/main/CONVENTIONS.md#folders)

**Do you have any additional context?**
Referred to here:
https://github.com/opensearch-project/opensearch-plugins/issues/174

**Comment by Yury-Fridlyand** [comment]
I think it was already fixed in #670

**Comment by dai-chen** [comment]
@mnkugler anything else needed if this is already fixed as Yury mentioned?

**Comment by mnkugler** [comment]
@Yury-Fridlyand @dai-chen no we can close the issue. Thank you both!
