### ISSUE TITLE
[BUG] `ROUND` function returns FP result for FP value

### ISSUE THREAD

**Issue by Yury-Fridlyand** [opensearch-project/sql#1138]
**What is the bug?**
https://github.com/opensearch-project/sql/blob/43ceda18930c459ff4f3c50651d98063f4bcc334/core/src/main/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunction.java#L411-L419
https://github.com/opensearch-project/sql/blob/43ceda18930c459ff4f3c50651d98063f4bcc334/core/src/main/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunction.java#L397-L398

**How can one reproduce the bug?**
```
opensearchsql> select typeof(round(1.1)), round(1.1);
fetched rows / total rows = 1/1
+----------------------+--------------+
| typeof(round(1.1))   | round(1.1)   |
|----------------------+--------------|
| DOUBLE               | 1.0          |
+----------------------+--------------+
```

**What is the expected behavior?**
`ROUND` function should return an integer value (`INTEGER` or `LONG`).

It may happen that returned FP value is not an integer number (has digits after the point).

**Comment by matthewryanwells** [comment]
@Yury-Fridlyand Currently if you put a double in you get a double out, and if you put a long in you get a long out.

If you put a double into round(x) should it return a long always? If you put a double into round(x, y) you can specify how many decimal points to return so sometimes it would have decimals and sometimes it wouldn't, should this always return a double?

**Comment by Yury-Fridlyand** [comment]
I expected `round(double x)` to return `long` and java's `Math.round` does. On another hand, MySQL returns `double` in that case, and we're aligning with MySQL.
Probably I got confused between these two behaviours and it is not a bug actually.
