### ISSUE TITLE
[DISCUSSION] Reduce amount of `ExprCoreType`s

### ISSUE THREAD

**Issue by Yury-Fridlyand** [opensearch-project/sql#1176]
**Is your feature request related to a problem?**
1. Do we need so much numeric `ExprCoreType`s?
2. -//- datetime `ExprCoreType`s?

**What solution would you like?**
Why not to leave only `LONG` and `DOUBLE` or `LONG`/`INT` and `FLOAT`/`DOUBLE`?
I propose to get rid of `BYTE` and `SHORT` types, map `byte` and `short` opensearch types to `INT`. Thus we can reduce amount of math/comparison functions registered and simplify widening rule processing. Further removing of `INT` and `FLOAT` and using only `LONG` and `DOUBLE` would increase memory usage (for storing those values only!), but increase performance.

`BYTE` of even `BIT`/`BOOL` uses same amount of memory in Java (SQL/JDBC) or even in C (ODBC)(unless you use `pragma pack` which reduces performance). Refs: [one](https://www.javamex.com/tutorials/memory), [two](https://github.com/openjdk/jol).

```console
$ java -Djdk.module.illegalAccess=deny -jar jol-cli.jar internals java.lang.Byte | grep 'Instance size'
Instance size: 16 bytes
$ java -Djdk.module.illegalAccess=deny -jar jol-cli.jar internals java.lang.Integer | grep 'Instance size'
Instance size: 16 bytes
$ java -Djdk.module.illegalAccess=deny -jar jol-cli.jar internals java.lang.Long | grep 'Instance size'
Instance size: 24 byte
```

Also having both `DATETIME` and `TIMESTAMP` `ExprCoreType`s is a bit confusing - they contain the same information. Both types don't store time zone information.

**What alternatives have you considered?**
N/A

**Do you have any additional context?**
N/A

**Comment by Yury-Fridlyand** [comment]
#126 is to support more date formats
This ticket to remove duplicated types.
`DATETIME` and `TIMESTAMP` contain completely the same info and adding extra complexity

**Comment by acarbonetto** [comment]
We can remove `DATETIME`, but there's no real benefit to removing `BYTE`/`SHORT`.
