### ISSUE TITLE
remove Workbench , JDBC, ODBC, CLI,   workflows and code

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/sql#1216]
**Is your feature request related to a problem?**

see https://github.com/opensearch-project/sql/issues/640

As part of the reorganization of the SQL plugin into multiple smaller plugins, the removed code that has become the new plugins
needs to be removed from the main SQL plugin that now becomes the backend plugin for the SQL projects

 
**What solution would you like?**

As part of the reorganization of the SQL plugin into multiple smaller plugins, the removed code that has become the new plugins
needs to be removed from the main SQL plugin that now becomes the backend plugin for the SQL projects
SQL projects include:
 - https://github.com/opensearch-project/sql  -- backend support for all SQL/PPL Api
 - https://github.com/opensearch-project/sql-jdbc -- JDBC driver support for opensearch as backend 
 - https://github.com/opensearch-project/sql-odbc -- ODBC driver support for opensearch as backend 
 - https://github.com/opensearch-project/sql-cli -- command line Interface for interaction with the SQL backend
 - https://github.com/opensearch-project/dashboards-query-workbench -- fornt-end support
 

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by dai-chen** [comment]
Just a kindly reminder, please pay attention to the dependency between SQL and other components. For example, SQL comparison test task depends on JDBC driver on source code level. Doctest may also depend on SQL CLI.
