### ISSUE TITLE
Baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions

### ISSUE THREAD

**Issue by dblock** [opensearch-project/sql#1337]
Follow https://github.com/opensearch-project/.github/issues/125 to baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions.

Close this issue when:

1. [MAINTAINERS.md](MAINTAINERS.md) has the correct list of project maintainers.
2. [CODEOWNERS](CODEOWNERS) exists and has the correct list of aliases.
3. Repo permissions only contain individual aliases as collaborators with maintain rights, admin, and triage teams. 
4. All other teams are removed from repo permissions.

If this repo's permissions was already baselined, please confirm the above when closing this issue.

**Comment by dblock** [comment]
You have 19 maintainers in actual permissions, please work with admin to fix.
![Screenshot 2023-03-23 at 11 07 56 AM](https://user-images.githubusercontent.com/542335/227246886-320c8dab-3fac-4db4-892f-3b3ae254f3ed.png)

**Comment by Yury-Fridlyand** [comment]
With most recent changes I can merge a PR with no approvals.
