### ISSUE TITLE
[Testing Confirmation] Confirm current testing requirements 

### ISSUE THREAD

**Issue by stephen-crawford** [opensearch-project/sql#1360]
As part of the discussion around implementing an organization-wide testing policy, I am visiting each repo to see what tests they currently perform. I am conducting this work on GitHub so that it is easy to reference. 

Looking at the SQL repository, it appears there is 

| Repository  | Unit Tests | Integration Tests | Backwards Compatibility Tests | Additional Tests | Link | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | 
| SQL | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | Checkstyle, Jacoco (100% coverage required), Comparison Tests, Link checker, Certificate of Origin  | https://github.com/opensearch-project/sql/issues/1360 | 

If there are any tests I missed or anything you think all repositories in OpenSearch should have for testing please respond to this issue with details.

**Comment by Yury-Fridlyand** [comment]
The [main CI workflow](https://github.com/opensearch-project/sql/actions/workflows/sql-test-and-build-workflow.yml) runs:
- Unit tests
- Integration tests
- BWC tests
- Checkstyle - code style verification
- Jacoco - code coverage validation with 100% coverage requirement (there are exceptions for few files)
- Doctests - validation of examples given in documentations
- Comparison test - behavior validation compared with other databases (H2 and SQLite)

**Comment by scrawfor99** [comment]
Hi @Yury-Fridlyand, thank you for following up. I will adjust the notes for this to reflect what you run. For these tests do you feel any/all should be required across the organization?

**Comment by Yury-Fridlyand** [comment]
I think all java projects have checkstyle and jacoco.
Other projects could have test coverage and code style provided by other tools (jacoco is java specific), but huge amount of work is needed to satisfy coverage/style requirements.

**Comment by scrawfor99** [comment]
Thank you for the response, I will jot that down for the overall issue!

**Comment by Swiddis** [comment]
Looks like this is done -- reopen if needed
