### ISSUE TITLE
[BUG] New engine doesn't support duplicated identifiers in the SELECT clause

### ISSUE THREAD

**Issue by GumpacG** [opensearch-project/sql#1382]
**What is the bug?**
New engine doesn't support duplicated identifiers in the `SELECT` clause. This causes a legacy IT to fail when it runs on the new engine. https://github.com/opensearch-project/sql/blob/main/integ-test/src/test/java/org/opensearch/sql/legacy/QueryIT.java#:~:text=selectAllWithFieldReturnsAll

**How can one reproduce the bug?**
1. Query `SELECT *, int0 from calcs`
2. See error 
```{
  "error": {
    "reason": "Invalid SQL query",
    "details": "Multiple entries with same key: int0=1 and int0=1",
    "type": "IllegalArgumentException"
  },
  "status": 400
}
```

**What is the expected behavior?**
The output should be similar to Legacy where all columns are included in the result

**What is your host/environment?**
 - OpenSearch version 2.x

**Comment by Yury-Fridlyand** [comment]
A duplicate of https://github.com/opensearch-project/sql/issues/785?

**Comment by GumpacG** [comment]
> A duplicate of #785?

Yes, closing this issue. Thanks!
