### ISSUE TITLE
[BUG]Syntax error in ppl commands redirecting to blank page

### ISSUE THREAD

**Issue by rbhavna** [opensearch-project/sql#1409]
**What is the bug?**
New ppl commands have been introduced by ml-commons plugin to allow users to process the queried data from index before performing ML and AD operations. 

We recently found out a bug when sending such ppl requests on OS dashboards. Whenever there is a syntax error in the ppl request, instead of throwing error to the user, the page just goes blank(refer to the screenshots attached) which is not desirable. When sending the same requests on other platforms like postman, everything works fine and error message is thrown to the user.

**How can one reproduce the bug?**
1. Go to OpenSearch Dashboards
2. Go to Dev Tools
3. Send a PPL API request with a syntax error as shown below (the correct parameter to be used is "centroids" and not "centroid").
e.g: 
```
POST _plugins/_ppl
{
  "query": "source=iris_data | fields petal_length_in_cm,petal_width_in_cm | kmeans centroid=3"
}
```
5. The page goes blank as shown in the attachment 

**What is the expected behavior?**
Ideally, it should have thrown a syntax error as shown below:
```
{
  "error": {
    "reason": "Invalid Query",
    "details": "Failed to parse query due to offending symbol [centroid] at: 'source=iris_data | fields petal_length_in_cm,petal_width_in_cm | kmeans centroid' <--- HERE... More details: Expecting tokens in {<EOF>, 'CENTROIDS', 'ITERATIONS', 'DISTANCE_TYPE', '|'}",
    "type": "SyntaxCheckException"
  },
  "status": 400
}
```

This is happening for any PPL request that has some syntax error in its body. We have been seeing this behavior only with PPL commands and not with any other ML or AD APIs.

**Do you have any screenshots?**
<img width="1512" alt="Screenshot 2023-03-07 at 5 49 17 PM" src="https://user-images.githubusercontent.com/110800195/223598477-65dbb1f1-aef5-4923-94ca-aebf9679d77d.png">

**Comment by Yury-Fridlyand** [comment]
@rbhavna, thank you for posting the bug!
Could you please, rename it to be a bit more verbose?

**Comment by dai-chen** [comment]
@jngz-es may have some context?

**Comment by Swiddis** [comment]
Closing as stale / the query UI has changed a bit since this issue was opened so the bug is probably not relevant anymore
