### ISSUE TITLE
PPL - support 'SQL DESCRIBE TABLES' like functionality in PPL

### ISSUE THREAD

**Issue by mengweieric** [opensearch-project/sql#155]
**Is your feature request related to a problem? Please describe.**
Data may contain nested fields, therefore the osd client has to flatten nested fields, costing more time and resources to render fields in sidebar and suggestion list for query bar in a flattened manner

**Describe the solution you'd like**
Add functionality in Opensearch existing endpoint '_plugins/_sql' to flatten any object like nested fields

e.g. 
{
  'a': {
    'b': 'xx'
    'c': 'yy'
  }
}

will be flattened to
"schema":[
{
      "name": "a.b",
      "type": "keyword"
 },
{
      "name": "a.c",
      "type": "keyword"
 }]
datarows:[
 xx,
 yy
]

**Comment by dai-chen** [comment]
PPL describe is added in PR https://github.com/opensearch-project/sql/pull/646. Please reopen if anything else needed. Thanks!
