### ISSUE TITLE
[BUG] nested/object query with raw or csv format inserts unexpected newlines

### ISSUE THREAD

**Issue by acarbonetto** [opensearch-project/sql#1572]
**What is the bug?**
When using the `raw` or `csv` format output in SQL plugin, we expect each row of output to correspond with a row from the response.  

for example, from `SELECT nested(message.info), nested(comment.data) FROM nested_with_nulls`: 

Expected output: 
```
nested(message.info)|nested(comment.data)
|hh
b|aa
c|aa
c|ab
a|ab
zz|[aa, bb]
zz|[aa, bb]
|ee
a|ab
rr|[asdf, sdfg]
```

Actual output: 
```
nested(message.info)|nested(comment.data)
|hh
b|aa
c|aa
c|ab
a|ab
zz|[aa, bb
]
zz|[aa, bb
]
|ee
a|ab
rr|[asdf, sdfg
]
```

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by acarbonetto** [comment]
Note: this might be related to errors in Dashboard processing `raw` and `csv` format from the V2 engine (seems to work for the legacy engine).

**Comment by Yury-Fridlyand** [comment]
Detected the same issue with `csv` format without `nested`:
**V1**
```json
POST http://localhost:9200/_plugins/_sql?format=csv
{
    "query" : "select * from account where account_number = 70",
    "legacy": 1
}
```
```csv
account_number,firstname,address,balance,gender,city,employer,state,age,email,lastname
70,Deidre,685 School Lane,38172,F,Chestnut,Netplode,GA,33,deidrethompson@netplode.com,Thompson
```
**V2**
```json
POST http://localhost:9200/_plugins/_sql?format=csv
{
    "query" : "select * from account where account_number = 70"
}
```
```
account_number,firstname,address,balance,gender,city,employer,state,age,email,lastname
70,Deidre,
685 School Lane,
38172,F,Chestnut,Netplode,GA,
33,deidrethompson@netplode.com,Thompson
```

**Comment by matthewryanwells** [comment]
I've narrowed down that this bug is caused by the fact in legacy the header defines the content-type as `text/plain; charset=UTF-8` while in the new engine the content-type is `application/json; charset=UTF-8`
