### ISSUE TITLE
[BUG] Unable to run queries in documentation

### ISSUE THREAD

**Issue by ksco92** [opensearch-project/sql#1575]
**What is the bug?**
A clear and concise description of the bug.

I have AWS OS cluster running version 2.3. I am unable to run the following queries when I make an HTTP request:

```
POST /_plugins/_sql
{
  "query": "select current_date();"
}

POST /_plugins/_sql
{
  "query": "select curdate();"
}

POST /_plugins/_sql
{
  "query": "select sysdate();"
}
```

All of them return the same:

```
{
  "error": {
    "reason": "Invalid SQL query",
    "details": "",
    "type": "NullPointerException"
  },
  "status": 400
}
```

Allo those queries are actually copied from the docs: [https://github.com/opensearch-project/sql/blob/main/docs/user/dql/functions.rst](https://github.com/opensearch-project/sql/blob/main/docs/user/dql/functions.rst#current-date)

This also happens in the query workbench in the UI, running:

`select sysdate();`

Returns:

`Select sysdate(): Bad Request, this query is not runnable. `

**How can one reproduce the bug?**

It can be reproduced by spinning up a OS cluster on 2.3 and sending a request with any of the queries above.

**What is the expected behavior?**
The queries should return the expected results listed in the documentation.

**What is your host/environment?**
 - OS: AWS
 - Version 2.3
 - Plugins: sql

**Do you have any screenshots?**
<img width="745" alt="Screen Shot 2023-04-24 at 12 51 04 PM" src="https://user-images.githubusercontent.com/30414016/234101121-151b96be-6ca8-4873-97c3-8849f40977cf.png">
<img width="748" alt="Screen Shot 2023-04-24 at 12 51 33 PM" src="https://user-images.githubusercontent.com/30414016/234101218-b2f8a479-aa90-4ae5-970c-2cd6ea8a73e5.png">
<img width="761" alt="Screen Shot 2023-04-24 at 12 51 58 PM" src="https://user-images.githubusercontent.com/30414016/234101303-714b4cca-59a2-4ff4-ace9-0c08357953e1.png">
<img width="564" alt="Screen Shot 2023-04-24 at 12 52 39 PM" src="https://user-images.githubusercontent.com/30414016/234101459-a4ad76d2-563f-473b-9d4a-0bfe1af99f0c.png">

**Do you have any additional context?**
The requests are SigV4 signed and sent via the elasticsearch plugin from DataGrip. Other queries run properly:

```
POST /_plugins/_sql
{
  "query": "select count(*) from my_alias limit 1;"
}
```

Returns:

```
{
  "schema": [
    {
      "name": "count(*)",
      "type": "integer"
    }
  ],
  "datarows": [
    [
      12315361
    ]
  ],
  "total": 1,
  "size": 1,
  "status": 200
}
```

**Comment by Yury-Fridlyand** [comment]
@ksco92,
Thank you for reporting that. It is weird, `sysdate`, `current_date` and `curdate` were released prior to 2.3.
Did you upgrade your cluster from older version to 2.3?

**Comment by ksco92** [comment]
@Yury-Fridlyand no, it was recently created with CDK directly on 2.3. I actually have this issue in 6 different clusters, all of different sizes, across 5 different AWS accounts and 2 different regions.

**Comment by ksco92** [comment]
IDK if this is relevant here, but I filed this too: 

https://github.com/opensearch-project/sql-jdbc/issues/67

**Comment by Yury-Fridlyand** [comment]
Can you share please your CDK script if possible? I'd like to re-run it and reproduce the issue.
Please, delete all sensitive data prior to sharing.

**Comment by ksco92** [comment]
@Yury-Fridlyand  Decoupling the infrastructure sensitive details is a little complicated, but here is the actual Construct that creates the domain. After this, there are no settings changed at all:

```
this.domain = new Domain(this, `OpenSearchDomain${props.stage}${Stack.of(this).region}`, {
            version: EngineVersion.OPENSEARCH_2_3,
            domainName: `mydomain${props.stage}${Stack.of(this).region}`,
            ebs: {
                volumeSize,
                volumeType: EbsDeviceVolumeType.GP3,
            },
            enableVersionUpgrade: true,
            encryptionAtRest: {
                enabled: true,
                kmsKey: openSearchKmsKey,
            },
            enforceHttps: true,
            securityGroups: [
                this.openSearchSecurityGroup,
            ],
            vpc: props.vpc,
            vpcSubnets: [
                {
                    subnetType: SubnetType.PRIVATE_WITH_EGRESS,
                },
            ],
            zoneAwareness: {
                availabilityZoneCount: 2,
            },
            capacity: {
                masterNodes: 3,
                masterNodeInstanceType: instanceType,
                dataNodes: this.dataNodeCount,
                dataNodeInstanceType: instanceType,
            },
            logging: {
                slowSearchLogEnabled: true,
                appLogEnabled: true,
                slowIndexLogEnabled: true,
                auditLogEnabled: true,
            },
            fineGrainedAccessControl: {
                masterUserArn: cognitoObjects.authenticatedRole.roleArn,
            },
            nodeToNodeEncryption: true,
            tlsSecurityPolicy: TLSSecurityPolicy.TLS_1_2,
            removalPolicy: RemovalPolicy.DESTROY,
            accessPolicies: [
                new PolicyStatement({
                    actions: [
                        'es:ESHttp*',
                    ],
                    effect: Effect.ALLOW,
                    principals: [
                        adminRole,
                        cognitoObjects.authenticatedRole,
                        openSearchCustomerRole,
                    ],
                }),
            ],
            customEndpoint: {
                certificate: props.certificate,
                hostedZone: props.privateHostedZone,
                domainName: this.dnsName,
            },
            cognitoDashboardsAuth: {
                role: openSearchAdminRole,
                identityPoolId: cognitoObjects.identityPool.ref,
                userPoolId: cognitoObjects.userPool.userPoolId,
            },
        });
```

In summary, it's in a private VPC, uses cognito for dashboards auth and has custom endpoint. This is in CDK V2:

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_opensearchservice.Domain.html

**Comment by Yury-Fridlyand** [comment]
Awesome!
I'll try this sometime later. Sorry, I can't make a promise.

**Comment by Yury-Fridlyand** [comment]
@ksco92,
I just re-checked all things. Implementation of `sysdate`, `curdate` and other now-like functions was done in #754 on 2022-09-22, but OpenSearch 2.3 was released on 2022-09-14.
Unfortunately, there is a bit of mess in our release notes and dates when release posted on the repository don't match actual release dates.
Please, take into account that documentation on repository versioned by git. You posted a link to SQL functions on `main` branch, it contains all things exist in the SQL plugin, even something not released in upcoming 2.7 version. To see what is supported by 2.3, follow [this link](https://github.com/opensearch-project/sql/blob/2.3/docs/user/dql/functions.rst).

**Comment by Yury-Fridlyand** [comment]
I'm closing this issue for now. Please, try updating your OpenSearch cluster if these functions are essential for you.
Feel free to comment, re-open or open a new issue if you need to.

**Comment by ksco92** [comment]
@Yury-Fridlyand this was helpful thanks!

One last question, did I miss this detail just because the OS docs are not versioned?

**Comment by Yury-Fridlyand** [comment]
They are versioned by git. Select a version in the branch selector on the left:
https://github.com/opensearch-project/sql/blob/main/docs/user/dql/functions.rst#current-date

![image](https://user-images.githubusercontent.com/88679692/234445711-447fe60a-8f2b-40fb-b1c1-067a02d4f3a6.png)
