### ISSUE TITLE
can not download build-tools-1.0.0

### ISSUE THREAD

**Issue by LuXugang** [opensearch-project/sql#161]
Hi，
    while building project, in build.gradle,  could not download build-tools-1.0.0.pom from mavenLocal()、 mavenCentral()、 or jcenter()
could I get some suggestion？

**Comment by chloe-zh** [comment]
Hi @LuXugang please try out the following method:
1. Clone the OpenSearch source code from https://github.com/opensearch-project/OpenSearch. If you need to build 1.0.0 artifact, please check out the 1.0.0 branch. Or if you want to build 1.0.0.0, just remain at the main branch.
2. Build the 1.0.0 artifacts as dependencies by run command `./gradlew publishToMavenLocal -Dopensearch.version=1.0.0`, or replace with 1.0.0.0 regarding the version you are using
3. Retry the ./gradlew build command in SQL plugin after the above build succeeds

**Comment by LuXugang** [comment]
Thanks @chloe-zh

**Comment by dblock** [comment]
Tracking https://github.com/opensearch-project/opensearch-build/issues/20 to get dependencies into Maven central.
