### ISSUE TITLE
Review Usages of actionGet API Call

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/sql#165]
**Describe the bug**
Review usages of actionGet API calls so that this API if being called in a single threaded pool should use timeouts or should be called asynchronously. 

PRs in alerting (https://github.com/opensearch-project/alerting/pull/130) and index management (https://github.com/opensearch-project/index-management/pull/100) where we have replaced the usages of the actionGet API calls which are blocking in nature and block the execution of the program with the callback listeners for the API call response. Using this API with time outs is okay but the execution should be made asynchronous. 

Sample Usages: 

https://github.com/opensearch-project/sql/blob/635581040f79aa09c5cbaf2d4b5cb65b8dd784e5/opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClient.java#L120-L121

https://github.com/opensearch-project/sql/blob/635581040f79aa09c5cbaf2d4b5cb65b8dd784e5/legacy/src/main/java/org/opensearch/sql/legacy/executor/multi/MinusExecutor.java#L221

We should review all such usages.

**Comment by chloe-zh** [comment]
@aditjind Thanks for providing the details. Just would like to confirm that if we should start to fix this issue by ourselves, or you have drafted some PR for it? (since I saw you have created the alerting and ism PRs...) Thanks!

**Comment by aditjind** [comment]
Hey @chloe-zh, It's a straight-forward change. I don't have any PRs for SQL Plugin atm but I ll be happy to guide you through you it. :)

**Comment by chloe-zh** [comment]
@aditjind Ok great, then we will start on it asap! Thanks a lot!

**Comment by penghuo** [comment]
@aditjind could you give us more background why the async call is required? actually, SQL plugin use the [dedicated sql-worker threadpool](https://github.com/opensearch-project/sql/blob/main/plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java#L140).

**Comment by aditjind** [comment]
I understand if its executing in a scalable thread-pool which wouldn't block the caller program but the Plugin [best practices](https://github.com/opensearch-project/opensearch-plugins/blob/main/STANDARDS.md#use-asynchronous-method-invocation) guide suggests using synchronous method calls wherever applicable.

**Comment by vamsi-amazon** [comment]
Closing this issue as all the rest APIs in SQL are delegated to thread pool and no blocking action is performed on Transport thread.
