### ISSUE TITLE
New response format to support visualization 

### ISSUE THREAD

**Issue by chloe-zh** [opensearch-project/sql#168]
**Is your feature request related to a problem? Please describe.**
The observability visualization uses the SQL plugin as the query engine and consumes the PPL component of this plugin as the search language. The existing protocols are mostly to provide good service for the JDBC/ODBC connectors, but the frontend still needs to do much preprocessing before rendering the visualizations.

**Describe the solution you'd like**
The detailed proposal is noted in the comments of issue #162 

**Describe alternatives you've considered**
Pending discussion for alternatives.

**Additional context**
See #162 for details.

**Comment by dai-chen** [comment]
Closing and feel free to reopen if anything else needed. Thanks!
