### ISSUE TITLE
Support Parse and Extract field at search time

### ISSUE THREAD

**Issue by penghuo** [opensearch-project/sql#173]
**Is your feature request related to a problem? Please describe.**
Currently, PPL could query the field defined at index time (schema-on-write), PPL also support [define the field at query time](https://github.com/opendistro-for-elasticsearch/sql/blob/develop/docs/experiment/ppl/cmd/eval.rst)*(schema-on-read).* We want to the command that extract the field from text field by using regex expression at query time. for example, at index time, instead of extract the field from the raw log message, the user may choose to index all the raw log message as the text field. then during the query time, the user could parse and extract any field they want and do further processing. 

**Describe the solution you'd like**
```
E | *parse* <expression> [option] (<regex-expression>)
regex-expression: ?<fieldName[:fieldType]><regex>
```
* *E*: the input event stream.
* *expression*: An expression that evaluates to a string.
* option: TBD.
* *fieldName*: The name of a field to assign a value to, extracted from the string expression.
* *fieldType [Optional]:* The field type to be converted to. The default is string type.

**Describe alternatives you've considered**
* [SPL Rex Command](https://docs.splunk.com/Documentation/Splunk/8.0.2/SearchReference/Rex)
* [Loki Parser Expression](https://grafana.com/docs/loki/latest/logql/#parser-expression)
* [Kusto Parse Operator](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/parseoperator)

**Comment by dai-chen** [comment]
This is done in https://github.com/opensearch-project/sql/issues/359.
