### ISSUE TITLE
[FEATURE] Improve IT framework to configure nodes on Test case level.

### ISSUE THREAD

**Issue by penghuo** [opensearch-project/sql#1816]
**Is your feature request related to a problem?**
current RestTestIT does not support configure nodes for each test.
https://github.com/opensearch-project/sql/pull/1815

**What solution would you like?**
similar as [https://github.com/opensearch-project/sql/blob/a816a58dc888d6596b6f4c174d1d03bdff3[…]src/test/java/org/opensearch/sql/correctness/CorrectnessIT.java](https://github.com/opensearch-project/sql/blob/a816a58dc888d6596b6f4c174d1d03bdff3dc70d/integ-test/src/test/java/org/opensearch/sql/correctness/CorrectnessIT.java#L40)

**What alternatives have you considered?**
configure nodes in build.gradle

**Do you have any additional context?**

**Comment by Yury-Fridlyand** [comment]
@penghuo please add more details. It is impossible to reduce number of nodes into a cluster.
IT framework creates cluster and then discovers test cases.
It is good enough for you to set 2-3-5 nodes into the default IT cluster for all tests?

**Comment by acarbonetto** [comment]
This can be closed, as changes for this IT test are being reverted https://github.com/opensearch-project/sql/pull/2013
