### ISSUE TITLE
Support partial match in PPL

### ISSUE THREAD

**Issue by prashanttct07** [opensearch-project/sql#183]
**Is your feature request related to a problem? Please describe.**
PPL does not allow to run partial search, something like an equivalent of query-string or match query. 
Consider I have a document with as "title":"learning opensearch is fun"
Now if I want to get all the document where "fun" is present, as of now there is no way to run this kind of filter. And I need to run `search source=my_index | where title="learning opensearch is fun"`

**Describe the solution you'd like**
I would like the PPL to run query something like:
`search source=my_index | where title="fun"` or `search source=my_index | where title="*fun*"`
And above query would get me if it matches the document with partial data on title. 

**Describe alternatives you've considered**
Instead of using PPL, I am using regular GET API with query_string/match query

**Comment by anirudha** [comment]
thanks pls review https://github.com/opensearch-project/sql/issues/182

**Comment by dai-chen** [comment]
@prashanttct07 Thanks for reporting the issue! The full text search function you mentioned is already supported in PPL. Please check out https://github.com/opensearch-project/sql/blob/main/docs/user/ppl/functions/relevance.rst
