### ISSUE TITLE
[FEATURE] Javadocs should be properly formatted

### ISSUE THREAD

**Issue by MitchellGale** [opensearch-project/sql#1913]
[Documentation for Javadocs](https://www.oracle.com/ca-en/technical-resources/articles/java/javadoc-tool.html)

Some files with incorrectly formatted Javadocs that need to have formatting fixed:
`core/src/main/java/org/opensearch/sql/analysis/ExpressionReferenceOptimizer.java`
`core/src/main/java/org/opensearch/sql/analysis/SelectExpressionAnalyzer.java`
`core/src/main/java/org/opensearch/sql/ast/dsl/AstDSL.java`
`core/src/main/java/org/opensearch/sql/data/type/WideningTypeRule.java`

**Example:**
From `core/src/main/java/org/opensearch/sql/data/type/WideningTypeRule.java`

current JavaDoc is formatted as:
```
/**
 * The definition of widening type rule for expression value.
 * ExprType     Widens to data types
 * INTEGER      LONG, FLOAT, DOUBLE
 * LONG         FLOAT, DOUBLE
 * FLOAT        DOUBLE
 * DOUBLE       DOUBLE
 * STRING       STRING
 * BOOLEAN      BOOLEAN
 * ARRAY        ARRAY
 * STRUCT       STRUCT
 */
````

It should be formatted with a table as:
```
/**
 * The definition of widening type rule for expression value.
 * <table border="3">
 * <tr><th>ExprType</th><th>Widens to data types</th></tr>
 * <tr><td>INTEGER</td><td>LONG, FLOAT, DOUBLE</td></tr>
 * <tr><td>LONG</td><td>FLOAT, DOUBLE</td></tr>
 * <tr><td>FLOAT</td><td>DOUBLE</td></tr>
 * <tr><td>DOUBLE</td><td>DOUBLE</td></tr>
 * <tr><td>STRING</td><td>STRING</td></tr>
 * <tr><td>BOOLEAN</td><td>BOOLEAN</td></tr>
 * <tr><td>ARRAY</td><td>ARRAY</td></tr>
 * <tr><td>STRUCT</td><td>STRUCT</td></tr>
 * </table>
 */
```

**Comment by acarbonetto** [comment]
Closing this ticket.  This needs to be completed as part of https://github.com/opensearch-project/sql/issues/1101.
