### ISSUE TITLE
[BUG] Improve error response codes.

### ISSUE THREAD

**Issue by vamsi-amazon** [opensearch-project/sql#2035]
Currently all the internal errors throw Service Unavailable exception which is not apt and should throw internal server failure instead.
Code Pointer: https://github.com/opensearch-project/sql/blob/main/plugin/src/main/java/org/opensearch/sql/plugin/rest/RestPPLQueryAction.java#L148

The ask of this issue is to fix these error response codes in both sql and ppl APIs.

**Comment by penghuo** [comment]
* Internal Server error should return 500
