### ISSUE TITLE
Unable to quote the identifiers with double quotes in workbench [BUG]

### ISSUE THREAD

**Issue by chloe-zh** [opensearch-project/sql#217]
Unable to execute the queries if the identifiers are quoted with double quotes, even though it works in SQL/PPL plugin itself. Single quotes work though.
Example:
```
SHOW tables LIKE "%";
```

Possible reason: the workbench does not insert escape char (`\`) for the double quote (")

**Comment by joshuali925** [comment]
this will also be fixed by #305, similar to #194
