### ISSUE TITLE
[Refactor] Manage Spark job parameter for different query

### ISSUE THREAD

**Issue by dai-chen** [opensearch-project/sql#2192]
**Is your feature request related to a problem?**

Different query requires different Spark job submit parameters.

**What solution would you like?**

1. `CREATE` statement:
    a. Set `execution-timeout-minutes` to 0 so EMR-S won't time out the streaming job at background
    b. Disable DRA (Spark dynamic resource allocator) because it only works well for long-running batch job
    c. [TBD] Flint config that specifies which Env variable to populate to Flint metadata, such as EMR-S job info
2. `SELECT` statement 

Also think about if any flexible way to manage these parameters in case of changes in future.

**Comment by penghuo** [comment]
Replace Jar with Maven repository. https://github.com/opensearch-project/sql/blob/main/spark/src/main/java/org/opensearch/sql/spark/data/constants/SparkConstants.java
