### ISSUE TITLE
[BUG] S3Glue connector requires region for basicauth and noauth

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/sql#2197]
**What is the bug?**
S3Glue shouldn't require region when using basicauth or noauth

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by penghuo** [comment]
close by https://github.com/opensearch-project/sql/pull/2190.
