### ISSUE TITLE
[QUESTION] Inject MS SQL data into OpenSearch dashboard

### ISSUE THREAD

**Issue by PatrickB100** [opensearch-project/sql#240]
Hi Guys, 

I'm sorry for using the bugs function to raise a question but i have no idea how to do it in another way. 

Currently i am looking for an option to use data from my current Microsoft SQL server in OpenSearch. Is there a way to handle this? 

Apologies and thanks in advance,
Patrick

**Comment by penghuo** [comment]
Feel free to reopen this issue.
