### ISSUE TITLE
sql-cli tool is not published as an pipy module

### ISSUE THREAD

**Issue by Yury-Fridlyand** [opensearch-project/sql#243]
**Is your feature request related to a problem? Please describe.**
I'm tried to follow guide published in [readme for sql-cli](https://github.com/opensearch-project/sql/tree/main/sql-cli#install). It says 
> 2. Install the CLI:
`pip3 install opensearch-sql-cli`

Actually, the module is not published in [pipy](pipy.org) repository.

**Describe the solution you'd like**
Please, publish the module on [pipy](pipy.org).

**Describe alternatives you've considered**
As an alternative option, a link to download a standalone package (pip module or whatever else) could be published in the readme. It should be followed by the installation instructions.

**Additional context**
Please, consider updating animated gif. I tried to follow it and started opendistro sql-cli tool, which is incompatible with opensearch.
*UDP*: an automated publish of newer builds is always welcomed.

Thank you.

**Comment by zhongnansu** [comment]
https://pypi.org/project/opensearchsql/
