### ISSUE TITLE
[BUG] Cancel API doesn't restrict cancel operation on streaming job

### ISSUE THREAD

**Issue by dai-chen** [opensearch-project/sql#2430]
**What is the bug?**

Cancel API doesn't restrict the job type to to cancelled. If user runs cancel API with streaming job, the index state will be `REFRESHING`. Later, `CREATE` index statement with same index name will fail.

**How can one reproduce the bug?**

1. Create a skipping index
2. Cancel with the job ID
3. Create the skipping index again

**What is the expected behavior?**

For streaming job, user should always use `DROP` index statement which cancels the EMR-S job and move index state to `DELETED`. Cancel API should reject cancel request on streaming job. In this way, `CREATE` index statement can pass without issue.

**What is your host/environment?**
 - OS: 2.11

**Comment by dai-chen** [comment]
If we want to support cancel, PPL should trigger a new Flint Spark API, such as `CANCEL INDEX JOB` (as opposed to current `RECOVER INDEX JOB`). This command will stop the streaming job and transit index state back to `ACTIVE`.

**Comment by penghuo** [comment]
does create skipping index failed in step expected?
```
Create a skipping index
Cancel with the job ID
Create the skipping index again
```

**Comment by penghuo** [comment]
## Cancel API definition
The cancellation of the "create skipping index" statement would typically mean instructing the system to stop the index creation process that has been initiated by the above statement. Depending on where in the process the cancellation request is made, this can entail different things:

* Before Index Creation Completes: If the cancellation request is made while the index is still being created, it would ideally halt the creation process. This means the index would not be created, or if partially created, the system should ideally roll back any changes made up to that point.
* After Index Creation but During Auto-Refresh: If the index has already been created and the cancellation request pertains to the auto_refresh process, it would involve stopping the automatic refresh process associated with that index. The index itself would remain unless explicitly dropped, but it would no longer automatically update.

## Solutions
### alt-1 [preferred]
* if query result state is success, the query can not be cancelled. 
* if query is not executed, the query can be cancelled.
  * `CREATE SI/CI/MV (auto_refresh=true)` is submitted as EMR-S job, it is considered as executed when job is submitted, 
* if query is executing, 
  * if it is select query, it can be cancelled. https://github.com/opensearch-project/opensearch-spark/issues/243
  * if it is refresh query, it can be cancelled.
* limitation:`CREATE SI/CI/MV (auto_refresh=true)` can not be cancelled, error message is "Can not cancel create flint index query"

### alt-2 Support cancel `CREATE SI/CI/MV (auto_refresh=true)` if EMR-S job is not in executing state
* EMR-S client does not provide transitional get and cancel api.
