### ISSUE TITLE
[BUG][PPL] `isnotnull()` works but `ISNOTNULL()` doesn't work

### ISSUE THREAD

**Issue by joshuali925** [opensearch-project/sql#2431]
**What is the bug?**
`isnotnull()` works but `ISNOTNULL()` doesn't work

**How can one reproduce the bug?**
1. Go to playground
2. Run 
```
POST _plugins/_ppl
{
  "query": "source=.kibana | where ISNOTNULL(type)"
}
```
3. see `"{\n  \"error\": {\n    \"reason\": \"Invalid Query\",\n    \"details\": \"unsupported function name: isnotnull\",\n    \"type\": \"ExpressionEvaluationException\"\n  },\n  \"status\": 400\n}"`
4. change `ISNOTNULL` to lower case, query runs

**What is the expected behavior?**

**What is your host/environment?**
 - OS: [e.g. iOS] linux
 - Version [e.g. 22] 2.11.0
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by LantaoJin** [comment]
Thanks for this issue, I am going to fix this.
