### ISSUE TITLE
Add Windows Support

### ISSUE THREAD

**Issue by dblock** [opensearch-project/sql#249]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/95, add Windows support.

- [ ] Passing CI on Windows
- [ ] Documentation

**Comment by derek-ho** [comment]
Waiting for review on: https://github.com/opensearch-project/sql/pull/907. Then will merge and close this ticket

**Comment by derek-ho** [comment]
Merged into 2.x, waiting for backport PR to be merged before I close this issue

**Comment by derek-ho** [comment]
Merged in PR and backport PR so closing this issue:
https://github.com/opensearch-project/sql/pull/967
https://github.com/opensearch-project/sql/pull/907
https://github.com/opensearch-project/sql/pull/962
