### ISSUE TITLE
[BUG] Observability-Metrics fails to render page with Prometheus data source metric selected

### ISSUE THREAD

**Issue by lyradc** [opensearch-project/sql#2541]
**What is the bug?**
With a Prometheus data source added the Observability -> Metrics will show the available metrics from this data source. However when a metric is selected the page becomes mostly empty and errors are thrown in the browser console.

**How can one reproduce the bug?**
1. Create a Prometheus data source (below ran from Dev Tools)
```
POST _plugins/_query/_datasources
{
  "name": "prometheus",
  "connector": "prometheus",
  "properties": {
    "prometheus.uri": "https://prometheus.url.com/",
    "prometheus.auth.type": "basicauth",
    "prometheus.auth.username": "username",
    "prometheus.auth.password": "password"
  },
  "allowedRoles": []
}
```
2. Navigate to Observability -> Metrics
3. Wait for the list of available metrics to populate
![image](https://github.com/opensearch-project/sql/assets/101164522/d1fa132f-8674-42f9-89ce-f93058bc7bee)

4. Click on any metric, a moment later the page clears
![image](https://github.com/opensearch-project/sql/assets/101164522/fcfaa8b5-8020-4ff7-8c2f-591e5cd6cf1c)

When the page clears the following errors present in the browser console
![image](https://github.com/opensearch-project/sql/assets/101164522/003814ac-193f-43ab-9b3e-68a286e84f25)

**What is the expected behavior?**
When a metric is selected from Observability -> Metrics I expect to see a summary of the metric similar to the screenshots in https://opensearch.org/docs/latest/observing-your-data/prometheusmetrics/

**What is your host/environment?**
 - OS: Docker deployed on CentOS7
 - Version 2.12.0
 - Browser: Chrome version 122.0.6261.95 (Official Build) (64-bit)
 - Relevant Plugins:
 opensearch-sql version 2.12.0.0
 opensearch-observability version 2.12.0.0

**Comment by lyradc** [comment]
Possibly a factor, our Prometheus instance contains >1k metrics across ~600 servers.

**Comment by penghuo** [comment]
@vamsi-amazon  please take a look.

**Comment by HungryHowies** [comment]
I'm having the same issue  on OS/OSD v2.12.0 on Ubuntu 22.0.4

- I connected to Prometheus in the Data source section

![image](https://github.com/opensearch-project/sql/assets/22652276/c47cf808-cb00-49fe-9c22-a8b415ce3c35)

- Checked my datasource index set…

![image](https://github.com/opensearch-project/sql/assets/22652276/2844ff43-a897-4830-9eac-c76d507ed1a4)

- On the left Pane Observability → Metrics I see this

![image](https://github.com/opensearch-project/sql/assets/22652276/f05d8610-5760-42fd-8d67-c312a9309687)

- If I click on any one of those metrics or I click on Query Data  link  I see this…

![image](https://github.com/opensearch-project/sql/assets/22652276/64098dbd-afcf-4716-817c-db06a1a5f64a)

**Comment by akshatmisra198808** [comment]
Same has been happening with my environment. I would like to know if I can revert back to older version, will that help? Also, I want to validate if the data source(via api or dev tool) has the data saved(prometheus). I want to use grafana opensearch plugin (https://grafana.com/grafana/plugins/grafana-opensearch-datasource/) to visualize the data for my June release. I want to get the data from opensearch.

**Comment by nateynateynate** [comment]
I can't even make it this far. I've got prometheus and the node_exporter running, but setting up the data source then viewing data sources fails. 

![image](https://github.com/opensearch-project/sql/assets/96254688/c25d4ee2-90b9-4280-a30c-6ff4435ba778)
![image](https://github.com/opensearch-project/sql/assets/96254688/2cbb9abf-5e3e-430e-afa5-7388be48da07)
![image](https://github.com/opensearch-project/sql/assets/96254688/5202cf19-7908-4183-b5e7-890ed531b088)

Following the instructions here will get you to this point: https://opensearch.org/docs/latest/observing-your-data/prometheusmetrics/

**Comment by SergioFernandezCordero** [comment]
Hi I'm facing the same issue when adding prometheus datastore from the OpenSearch Management Portal. I have a local instance where I have easy to test, if that helps.

**Comment by HungryHowies** [comment]
> I can't even make it this far. I've got prometheus and the node_exporter running, but setting up the data source then viewing data sources fails.
> 
> ![image](https://private-user-images.githubusercontent.com/96254688/325774159-c25d4ee2-90b9-4280-a30c-6ff4435ba778.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwOTM2MTEsIm5iZiI6MTcxNDA5MzMxMSwicGF0aCI6Ii85NjI1NDY4OC8zMjU3NzQxNTktYzI1ZDRlZTItOTBiOS00MjgwLWEzMGMtNmZmNDQzNWJhNzc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDAxMDE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmZTA2ZDhhYjVkMjc0NTc1NzdlZDMxMjk4M2MxYzg2ZmFiMDM0ZTFhMTVhNzJkY2IxMjEyOTU2YjkzMGQ4MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4J7n0ix3JulQVPQW6kke63umdgvW-oexuzG4KtT-JUA) ![image](https://private-user-images.githubusercontent.com/96254688/325774182-2cbb9abf-5e3e-430e-afa5-7388be48da07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwOTM2MTEsIm5iZiI6MTcxNDA5MzMxMSwicGF0aCI6Ii85NjI1NDY4OC8zMjU3NzQxODItMmNiYjlhYmYtNWUzZS00MzBlLWFmYTUtNzM4OGJlNDhkYTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDAxMDE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzOWY2NWRkZWEzMzM0OGJmZmE2MWFjZjEzMjgwYjJjZjcwNjk1NzBmNGQ1OWE0OGRkMjk0ODEzNmZjMzA0YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8mYZAvhG4xj3RXG_BeGjJJMwI_fFudvtxmoWeM3-9qo) ![image](https://private-user-images.githubusercontent.com/96254688/325774373-5202cf19-7908-4183-b5e7-890ed531b088.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwOTM2MTEsIm5iZiI6MTcxNDA5MzMxMSwicGF0aCI6Ii85NjI1NDY4OC8zMjU3NzQzNzMtNTIwMmNmMTktNzkwOC00MTgzLWI1ZTctODkwZWQ1MzFiMDg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDAxMDE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlY2I2MTQ4MDVjZWU0ZGQyMTcxNmNhYWUzNWViNjU2MmQ1Mjg1ZWIyODJjZjg3NjVlYWI0MzNmYTNlMGE0MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rkoa8XxED-cy98JuII4hAvQSmWRecw_TiGQ5lDiPdBY)
> 
> Following the instructions here will get you to this point: https://opensearch.org/docs/latest/observing-your-data/prometheusmetrics/

Hey, So on  slack I talk to someone and even version 2.13 failed. I think  from what I understand this should be fixed on ver 2.14

**Comment by vamsi-amazon** [comment]
@HungryHowies  can you point me to the slack thread. Sorry for the delayed response, I will try to get this fixed asap. 
@nateynateynate , @HungryHowies 

> I'm having the same issue on OS/OSD v2.12.0 on Ubuntu 22.0.4
> 
> * I connected to Prometheus in the Data source section
> 
> ![image](https://private-user-images.githubusercontent.com/22652276/317955435-c47cf808-cb00-49fe-9c22-a8b415ce3c35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MjEyNDMsIm5iZiI6MTcxNDQyMDk0MywicGF0aCI6Ii8yMjY1MjI3Ni8zMTc5NTU0MzUtYzQ3Y2Y4MDgtY2IwMC00OWZlLTljMjItYThiNDE1Y2UzYzM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDIwMDIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyZTMzNjYzYmExZTUwODYzY2M0NzY4NTdiODY1MDAxN2ZjYjcwYmNhYjBjNzI4MjI2YmY4NDczNGMyZmEzOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BXFyxJm32NlOADo9pSCZc1xW6OZqlXtEdl5MIG6Ns6I)
> 
> * Checked my datasource index set…
> 
> ![image](https://private-user-images.githubusercontent.com/22652276/317955578-2844ff43-a897-4830-9eac-c76d507ed1a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MjEyNDMsIm5iZiI6MTcxNDQyMDk0MywicGF0aCI6Ii8yMjY1MjI3Ni8zMTc5NTU1NzgtMjg0NGZmNDMtYTg5Ny00ODMwLTllYWMtYzc2ZDUwN2VkMWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDIwMDIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMzRmODJhMmEwNzkwNGFjNTc2ZjBmNzE3NTI4Nzk4NzdkNjBiZTg5YzQ3OGI2NWNiZmQzYmRlNTkyNjdhMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V2vxJSyVwbBiMinqcME7aqU7neIywhqKzt0Isx2l-Qk)
> 
> * On the left Pane Observability → Metrics I see this
> 
> ![image](https://private-user-images.githubusercontent.com/22652276/317955680-f05d8610-5760-42fd-8d67-c312a9309687.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MjEyNDMsIm5iZiI6MTcxNDQyMDk0MywicGF0aCI6Ii8yMjY1MjI3Ni8zMTc5NTU2ODAtZjA1ZDg2MTAtNTc2MC00MmZkLThkNjctYzMxMmE5MzA5Njg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDIwMDIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhMWI4MTEzNTBlMGMwMWFmZjEwY2QwYzlhZmRhNWY2MzEzZmZiODAwZDA2ZDkwODZlOTZiZDM2NTE5MTg4NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jGHtFT8ZhSKQr3ChiQAlHLXVhIP04zTtIXlMhJ93jIw)
> 
> * If I click on any one of those metrics or I click on Query Data  link  I see this…
> 
> ![image](https://private-user-images.githubusercontent.com/22652276/317955765-64098dbd-afcf-4716-817c-db06a1a5f64a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MjEyNDMsIm5iZiI6MTcxNDQyMDk0MywicGF0aCI6Ii8yMjY1MjI3Ni8zMTc5NTU3NjUtNjQwOThkYmQtYWZjZi00NzE2LTgxN2MtZGIwNmExYTVmNjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDIwMDIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxN2NmNWI4NGJmZmRhNDEyMmNiMTRhNTAyZTQzOWQ4YmUwNDg0OTRlMjgxYWZkMDUwNWJkNDNlZDgzZWYzODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YcOHLsKgQh5JkKQTRzYftwoQ2OtrXMmWAl6s77gAhrw)
> 
> Once that happens I never can see metrics list again. I have tried Firefox and almost seen a visualization started and it went blank.

@HungryHowies  Sorry for the delayed response. do we have more details(console logs/har file)  to understan the issue better?

**Comment by AdaptiveStep** [comment]
Does the datasource prometheus in opensearch work for anyone? 

I can't make it work, it keeps saying:


```
{
  "status": 400,
  "error": {
    "type": "IllegalArgumentException",
    "reason": "Invalid Request",
    "details": "Async Query APIs are disabled. Please configure plugins.query.executionengine.spark.config in cluster settings to enable them."
  }
}
```

**Comment by nateynateynate** [comment]
> I can't make it work, it keeps saying:

I was also unable. I think our only current course of action is to wait until 2.14 releases. Here's the current release schedule: https://opensearch.org/releases.html

**Comment by vamsi-amazon** [comment]
@RyanL1997  did this get fixed in 2.14?

**Comment by HungryHowies** [comment]
I just install OS 2.14 and it start but no data

**Comment by RyanL1997** [comment]
> https://github.com/opensearch-project/sql/issues/2541#issuecomment-2078196267

This surfaced up again in current main and 2.14, which is introduced by: https://github.com/opensearch-project/dashboards-observability/pull/1739. We just did the fixes in main:
- https://github.com/opensearch-project/dashboards-observability/pull/1830

**Comment by SergioFernandezCordero** [comment]
Upgrading to 2.14 solved the problem for me. Thank you!
