### ISSUE TITLE
Does the JDBC driver support integration with tableau server?

### ISSUE THREAD

**Issue by gsjoy8888** [opensearch-project/sql#257]
Per the doc in https://github.com/opensearch-project/sql/blob/main/sql-jdbc/docs/tableau.md, Tableau Desktop support Opensearch integration with the sql jdbc driver. My question is, does this support also apply to Tableau Server? Or Tableau Server and Opensearch integration can only be supported by using ODBC driver?

Thanks!

**Comment by Yury-Fridlyand** [comment]
@gsjoy8888,
The Tableau connector uses SQL JDBC driver and it could be used for Tableau Server and Tableau Desktop both.
