### ISSUE TITLE
StringIndexOutOfBoundsException for LEFT() and RIGHT()[BUG]

### ISSUE THREAD

**Issue by guiangumpac** [opensearch-project/sql#266]
**Describe the bug**
StringIndexOutOfBoundsException is thrown when the second of argument of LEFT and RIGHT functions is greater than the length of the first argument.

Or for query issues:
1. Run the query 'SELECT LEFT("Hello", 6)'
2. See error 'StringIndexOutOfBoundsException'

**Expected behavior**
The output should be the whole string when the second argument is greater than or equal to the length of the string.

**Screenshots**
![image](https://user-images.githubusercontent.com/90278068/140551257-4e46dbcb-2d1a-4528-82f9-78c8d16b0143.png)

**Comment by chloe-zh** [comment]
Code changes for this fix: #285

**Comment by guiangumpac** [comment]
This issue affects TDVT tests:
- exprtests/standard\setup.string.left.real.txt
- exprtests/standard\setup.string.left.txt
- exprtests/standard\setup.string.right.real.txt
- exprtests/standard\setup.string.endswith.txt
- exprtests/standard\setup.string.startswith.txt
