### ISSUE TITLE
[BUG] DROP INDEX cancel FlintREPL job

### ISSUE THREAD

**Issue by penghuo** [opensearch-project/sql#2689]
**What is the bug?**
User submit DROP INDEX query, plugin cancel FlintREPL job. The imapct is if user submit query in same session, submitted query will in waiting state forever.

**How can one reproduce the bug?**
* T1: submit CREATE SKIPPING INDEX query with auto_refresh=false
* T2: submit DROP INDEX query,  make sure (T2-T1) < 3mins

unexpected result is
* FlintREPL EMR-S job is cancelled, indexState is REFRESHING

**What is the expected behavior?**
FlintREPL EMR-S job should not been cancelled.

**Do you have any additional context?**
[In SQL Plugin 2.13](https://github.com/opensearch-project/sql/blob/main/spark/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpDrop.java#L28), when user submit DROP INDEX query, plugin cancel EMR-S job even index state is EMTPY / ACTIVE. 

```
  public boolean validate(FlintIndexState state) {
    return state == FlintIndexState.REFRESHING
        || state == FlintIndexState.EMPTY
        || state == FlintIndexState.ACTIVE
        || state == FlintIndexState.CREATING;
  }
```

**Suggested solutions**
Alt-1. For CREATE INDEX, we could submit FlintJob instead of FlintREPL. 
Alt-2. Prevalidate indexState, only cancel Job when it is in Refreshing state.

**Comment by seankao-az** [comment]
Before refactoring the DML handler and FlintIndexOp, DROP index involved 2 steps: Cancel op and Delete op, and each has their own validation. ([cancel](https://github.com/opensearch-project/sql/blob/60058ce1de6db0c6c2278a2382b674ff6e1eb78c/spark/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpCancel.java), [delete](https://github.com/opensearch-project/sql/blob/60058ce1de6db0c6c2278a2382b674ff6e1eb78c/spark/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpDelete.java))
After refactoring, the two steps are merged and shared one same validation logic, which is incorrect.

Of the two solution proposed, Alt-1 using FlintJob has the disadvantage of sacrificing query latency. Executing the create index statement in FlintREPL will be way faster.
Alt-2 seems better. We can validate the index state to be Refreshing state before cancel.
