### ISSUE TITLE
[BUG] `str_to_date` does not work with two-digits year

### ISSUE THREAD

**Issue by LantaoJin** [opensearch-project/sql#2741]
**What is the bug?**
`str_to_date` function in https://opensearch.org/docs/latest/search-plugins/sql/functions/#date-and-time does not work with two-digits year ([RFC 822 date-time](http://www.w3.org/Protocols/rfc822/#z28) formatted). 

**How can one reproduce the bug?**
Make a similar query
```SQL
SELECT str_to_date('03-Jan-24', '%d-%b-%y');
```
returns
`0024-01-03 00:00:00`

**What is the expected behavior?**
Return `2024-01-03 00:00:00`

**What is your host/environment?**
 - Version: OpenSearch 2.14
 - Plugins: SQL

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by dblock** [comment]
[Catch All Triage - Attendees [1](https://github.com/dblock/), [2](https://github.com/krisfreedain), [3](https://github.com/andrross), [4](https://github.com/gkamat), [5](https://github.com/getsaurabh02)]
