### ISSUE TITLE
Case insensitive text search SQL

### ISSUE THREAD

**Issue by homli-admin** [opensearch-project/sql#2800]
Is there any way I can run this query with the SQL plugin?

`SELECT * FROM <index> WHERE col1 ILIKE '%test%"`?

I tried using UPPER(col1) LIKE UPPER('%test%') but it  doesn't look like its supported.

**Comment by LantaoJin** [comment]
Would you try to use `LIKE` replace the `ILIKE` in your query? The `LIKE` is case insensitive.

**Comment by homli-admin** [comment]
So it looks like it works if you convert what you're searching to lower case before. So `LIKE '%Here%` fails but `LIKE '%here%'` works (even if the real text is Here). I was able to make it work with a small hack like this.

**Comment by LantaoJin** [comment]
@homli-admin I could reproduce the issue you mentioned in old engine. A simple way to trigger a query using old engine is adding `?format=json`. Repro steps:
```
POST _bulk
{ "index" : { "_index" : "test_bulk2", "_id" : "1" } }
{ "a": "TesT search something", "query_id": 1, "id": 1}
# fail
POST /_plugins/_sql?format=json
{
  "query": "SELECT * FROM test_bulk2 WHERE a LIKE '%TesT%'"
}
# success
POST /_plugins/_sql
{
  "query": "SELECT * FROM test_bulk2 WHERE a LIKE '%TesT%'"
}
```

**Comment by LantaoJin** [comment]
Seems an OpenSearch bug, open https://github.com/opensearch-project/OpenSearch/issues/14712 to track.
