### ISSUE TITLE
Limit Spark SQL queries to SELECT  + FLINT commands when Lake Formation is enabled

### ISSUE THREAD

**Issue by asuresh8** [opensearch-project/sql#2907]
When using Lake Formation, OpenSearch should limit the Spark SQL queries to only SELECT to limit the capability of users to escalate privilege beyond what Lake Formation actually grants the user.

This proposal includes 2 main pieces:
1. Define a more limited ANTLR grammar that restricts SQL grammar to only SELECT, COVERING INDEX, and MATERIALIZED VIEW
2. If Lake Formation is enabled, validate that SQL is restricted to that grammar.

**Comment by penghuo** [comment]
OSD - QueryExplorer use `SHOW TABLE EXTENDED` and `SHOW DATABASES`, is it ok to allowlist them for LF datasource?

**Comment by asuresh8** [comment]
We need to double check to make sure LF permissions are honored for those commands.

**Comment by asuresh8** [comment]
This change should be pretty similar to https://github.com/opensearch-project/sql/pull/2790, where a different grammar file needs to be used that scopes down SQL commands. The ANTLR generated lexer for that grammar should be used to validate the query and throw an exception if grammar that is not permitted is used.
