### ISSUE TITLE
[BUG] `index` tag set to the EMRS job run is not correct

### ISSUE THREAD

**Issue by ykmr1224** [opensearch-project/sql#2908]
**What is the bug?**
`index` tag set to the EMRS job run does not include datasource name and schema when those are not explicitly specified in the query.
Example query: `CREATE MATERIALIZED VIEW mv1 AS ....`
In this case, `index` tag should be `flint_{datasourceName}_{schema}_mv1`, but it is set to `flint_mv1`

**How can one reproduce the bug?**
1. start async-query with `CREATE MATERIALIZED VIEW mv1 AS SELECT ...`
2. check EMR job run

**What is the expected behavior?**
`index` tag should look like `flint_{datasourceName}_{schema}_mv1`

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by dai-chen** [comment]
Flint grammar allows this because we can infer the current catalog and database in Spark. Probably we should consider validating and disallowing this in SQL plugin.

**Comment by noCharger** [comment]
> Flint grammar allows this because we can infer the current catalog and database in Spark. Probably we should consider validating and disallowing this in SQL plugin.

+1, since Plugin doesn't have the catalog info exposure

**Comment by anirudha** [comment]
expectation is the use full qualified names for create including a DB name
