### ISSUE TITLE
JDBC driver ADDDATE and SUBDATE issue[BUG]

### ISSUE THREAD

**Issue by ghost** [opensearch-project/sql#291]
**Describe the bug**
ADDDATE and SUBDATE results in null if the timestamp time result is 00:00:00.

**To Reproduce**
1. SELECT SUBDATE(TIMESTAMP('2010-04-12 01:00:00'), INTERVAL 0 HOUR)
2. See result being 2010-04-12 01:00:00
3. SELECT SUBDATE(TIMESTAMP('2010-04-12 01:00:00'), INTERVAL 1 HOUR)
4. See result being null

**Expected behavior**
Expected result should be 2010-04-12 00:00:00 or 2010-04-12.

**Additional context**
![image](https://user-images.githubusercontent.com/90278068/142488862-753c8819-fb53-41cc-9bd1-a5705ca4031a.png)
It returns a date when calling DATE() when we know that the result of the argument is null from the image above.
![image](https://user-images.githubusercontent.com/90278068/142488676-e4627b99-d56d-4fe9-b057-43d45984ea25.png)
SQL plugin returns datetime without time:
![image](https://user-images.githubusercontent.com/90278068/142489081-1e4920e2-3a6c-4f08-8dbb-1aa94bf5fd4f.png)

**Comment by guiangumpac** [comment]
In progress

**Comment by dai-chen** [comment]
Can we close this now?

**Comment by Yury-Fridlyand** [comment]
Fix is coming from https://github.com/Bit-Quill/opensearch-project-sql/pull/122. I'll close this.
