### ISSUE TITLE
[BUG] Pagination of index aliases is not supported - Re-opened

### ISSUE THREAD

**Issue by ctellechea2001** [opensearch-project/sql#2912]
Hi guys, I am re-opening this ticket that was opened a long time ago by MaxKsyunz reporting a bug using filter in aliases

https://github.com/opensearch-project/sql/issues/1398

It is possible to take a look? I have checked that in the latest version (2.15.0) the issues still happening using **filter in query using sql plugin to an alias**

![2024-08-07_16-28-11](https://github.com/user-attachments/assets/c01b3980-86af-45cf-a685-f6305f4072b9)

If you remove the filter everything looks fine.

![2024-08-07_16-30-29](https://github.com/user-attachments/assets/10cfcc1f-c6b3-46cd-8fc3-5ff7d967e489)

**Comment by dblock** [comment]
[Catch All Triage - [1](https://github.com/andrross), [2](https://github.com/dblock), [3](https://github.com/AmiStrn), [4](https://github.com/reta), [5](https://github.com/finnegancarroll)]

**Comment by aparajita31pandey** [comment]
Hi I would like to pick this @dblock  if its not picked by anyone

**Comment by aparajita31pandey** [comment]
I have fixed the issue in above pull request and tested it , but I am planning to add test cases also here

**Comment by ctellechea2001** [comment]
@aparajita31pandey Thank you so much for your help!!!
Do you know in which version/release will this fix available? 

Thanks again!!

**Comment by ctellechea2001** [comment]
@dblock @aparajita31pandey  Any update on the hotfix? Do you know in which version/release will this fix available?
Thanks a lot!
