### ISSUE TITLE
Unable to compare DATETIME and TIMESTAMP[BUG]

### ISSUE THREAD

**Issue by ghost** [opensearch-project/sql#294]
**Describe the bug**
Unable to compare DATETIME and TIMESTAMP for logical operators and CASE.

Or for query issues:'
1. Run the query 'SELECT TIMESTAMP(DATE("2010-04-12")) = SUBDATE(TIMESTAMP(DATE("2010-04-12")), INTERVAL 1 HOUR)'
2. See error "ExpressionEvaluationException"

**Expected behavior**
The SQL plugin should be able to compare DATETIME and TIMESTAMP or SUBDATE and ADDDATE should have output of type TIMESTAMP.

**Screenshots**
![image](https://user-images.githubusercontent.com/90278068/142569354-89379606-a2fb-4201-8fa7-b20e8bbad73a.png)

**Comment by dai-chen** [comment]
The root cause seems implicit conversion between DATETIME and TIMESTAMP is not supported. Code: https://github.com/opensearch-project/sql/blob/main/core/src/main/java/org/opensearch/sql/data/type/ExprCoreType.java#L58
