### ISSUE TITLE
[FEATURE] Add support for multi value fields.

### ISSUE THREAD

**Issue by vamsi-amazon** [opensearch-project/sql#2962]
Implement multivalue field support, allowing fields to contain multiple values for flexible data handling and querying. Update the query engine accommodate this feature. Ensure backward compatibility and update relevant APIs and UI components as needed.
This is a prerequisite task for building multi value field expand features and others.

**Comment by YANG-DB** [comment]
@vamsi-amazon please add example for optional syntax

**Comment by YANG-DB** [comment]
This needs a better description including examples and use case - closing util these prerequisites are fulfilled
