### ISSUE TITLE
[FEATURE] Add support for field summary command.

### ISSUE THREAD

**Issue by vamsi-amazon** [opensearch-project/sql#2963]
Implement a fieldsummary command to generate statistics for all fields in the events, including count, distinct count, min, max, and other relevant metrics. Ensure the command can handle various data types and provide options for customizing the summary output.

**Comment by YANG-DB** [comment]
@vamsi-amazon please add example for possible syntax

**Comment by YANG-DB** [comment]
closing this for duplication with [#3026](https://github.com/opensearch-project/sql/issues/3026)
