### ISSUE TITLE
[FEATURE] Add support for flattening nested and array objects.

### ISSUE THREAD

**Issue by vamsi-amazon** [opensearch-project/sql#2964]
Develop a flatten command to normalize complex, nested data structures. The command should expand nested objects and arrays into separate field-value pairs, with options to specify the depth of flattening and handling of array indices. Ensure compatibility with existing search and analysis features.

**Comment by YANG-DB** [comment]
@vamsi-amazon please add example for optional syntax

**Comment by kedbirhan** [comment]
i believe this issue is duplicate of #2652

**Comment by YANG-DB** [comment]
closing this for duplication with #3029
