### ISSUE TITLE
[BUG] "The following method is not supported in Schema: DAYSOFWEEK" returns 200 for http response

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/sql#311]
**Describe the bug**
```
curl -XPOST http://localhost:9200/_plugins/_sql -H 'Content-Type: application/json' -d '{"query" : "SELECT A, B FROM (SELECT `key` as A, DAYSOFWEEK(customer_first_name) AS B from opensearch_dashboards_sample_data_flights) opensearch_dashboards_sample_data_ecommerce;"}' -v
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9200 (#0)
> POST /_plugins/_sql HTTP/1.1
> Host: localhost:9200
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 180
> 
* upload completely sent off: 180 out of 180 bytes
< HTTP/1.1 200 OK
< content-type: application/json; charset=UTF-8
< content-length: 214
< 
{
  "error": {
    "reason": "There was internal problem at backend",
    "details": "The following method is not supported in Schema: DAYSOFWEEK",
    "type": "UnsupportedOperationException"
  },
  "status": 500
* Connection #0 to host localhost left intact
}* Closing connection 0
```
Is it supposed to return `200 `for http response?

**To Reproduce**

Or for query issues:
1. Create the index with test documents by 'POST ...'
2. Run the query 'SELECT ...'
3. See error

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by penghuo** [comment]
1. Function name should be `dayofweek` instead of `daysofweek`.
2. Every derived table must have its own alias. thus, should add `as T` for subquery.
 
The following query works as expected.
```
POST /_plugins/_sql
{
  "query": "SELECT A FROM (SELECT dayofweek(timestamp) as A FROM opensearch_dashboards_sample_data_logs LIMIT 1) as T"
}
```

**Comment by penghuo** [comment]
Error message is misleading.  Because NewSqlEngine throw syntax exception, then query fallback to old engine. Old engine doesn't support daysofweek function, then it throw daysofweek not supported exception.
