### ISSUE TITLE
[BUG] Not able to enable plugins.query.field_type_tolerance

### ISSUE THREAD

**Issue by archis99** [opensearch-project/sql#3200]
**What is the bug?**
I wanted to enable `plugins.query.field_type_tolerance` to properly get the array values in response. But while doing so, I'm getting the following error.

```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "transient setting [plugins.query.field_type_tolerance], not recognized"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "transient setting [plugins.query.field_type_tolerance], not recognized"
  },
  "status": 400
}
```

**How can one reproduce the bug?**
1. Call the below api
```
PUT _cluster/settings
{
  "transient" : {
    "plugins.query.field_type_tolerance" : true
  }
}
```

**What is your host/environment?**
Opensearch: 2.11

**Comment by Swiddis** [comment]
`plugins.query.field_type_tolerance` was introduced in version 2.18
