### ISSUE TITLE
Why aggregation still use ElasticsearchQueryRequest instead of ElasticsearchScrollRequest

### ISSUE THREAD

**Issue by chyun** [opensearch-project/sql#33]
ElasticsearchQueryRequest has a size limit(default is 200) which make aggregation did not work well. Apparently you know that cause I see the comment in class of ElasticsearchNodeClient:
```
  /**
   * TODO: Scroll doesn't work for aggregation. Support aggregation later.
   */
  @Override
  public ElasticsearchResponse search(ElasticsearchRequest request) {
    return request.search(
        req -> client.search(req).actionGet(),
        req -> client.searchScroll(req).actionGet()
    );
  }
```

And I see ElasticsearchScrollRequest is already there, but ElasticsearchIndexScan still use ElasticsearchQueryRequest in its constructor function:
```
  /**
   * Todo.
   */
  public ElasticsearchIndexScan(ElasticsearchClient client,
                                Settings settings, String indexName,
                                ElasticsearchExprValueFactory exprValueFactory) {
    this.client = client;
    this.request = new ElasticsearchQueryRequest(indexName,
            settings.getSettingValue(Settings.Key.QUERY_SIZE_LIMIT), exprValueFactory);
  }
```
I am wondering why.

**Comment by dai-chen** [comment]
Hi @chyun, `OpenSearchScrollRequest` seems not in use for now. Our engine interacts with OpenSearch by a single DSL request in `OpenSearchIndexScan` operator. As I understand, Scroll doesn't work with OpenSearch aggregation. Unless we do aggregation by physical operator in memory (which has severe performance degradation), Scroll won't solve the problem you mentioned.
