### ISSUE TITLE
Publish download link for JDBC Driver

### ISSUE THREAD

**Issue by davidcui1225** [opensearch-project/sql#335]
Publish download link for the JDBC driver independently from ODBC

**Comment by Yury-Fridlyand** [comment]
Isn't it a duplicate of #244?

**Comment by davidcui1225** [comment]
Not quite, the releases for JDBC and ODBC are being tracked separately and will be released independently of each other, so I created a separate issue for JDBC since that one is on track to be released first

**Comment by joshuali925** [comment]
closed by https://github.com/opensearch-project/project-website/pull/635, links are available on https://opensearch.org/artifacts
