### ISSUE TITLE
Perform manual testing for Power BI

### ISSUE THREAD

**Issue by ghost** [opensearch-project/sql#336]
Manual testing of visualizations is critical for Power BI Certification. The tasks are:
- Create test cases
- Perform manual tests
- Determine cause of failures

**Comment by dai-chen** [comment]
Is this task for query engine or JDBC/ODBC driver?

**Comment by Yury-Fridlyand** [comment]
It was a task for ODBC/PBI connector.
PBI connector already tested and released.
