### ISSUE TITLE
[BUG] link for SqlOdbcPBIConnector.mez not working

### ISSUE THREAD

**Issue by chouchoucha** [opensearch-project/sql#340]
Hello, 

Your link for download SqlOdbcPBIConnector.mez is failed. 
Where i can find the right link ? 
Thank to advance, 

Best Regards, 

Anne-Charlotte

**Comment by joshuali925** [comment]
Hi, is this what you are looking for? https://github.com/opensearch-project/sql/blob/main/bi-connectors/PowerBIConnector/bin/Release/SqlOdbcPBIConnector.mez

and could you let us know where you are seeing the the broken link? Thanks

**Comment by Yury-Fridlyand** [comment]
Fixed by #665.
