### ISSUE TITLE
[BUG] Link to 'PPL Documentation' leads to wrong page but not 404. 

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/sql#350]
**Describe the bug**

Wrong link destination. 

**To Reproduce**

1. Go to the Query Workbench
2. Select 'PPL' as the query language. 
3. Click 'PPL Documentation'
4. Arrive at https://opensearch.org/docs/latest/

**Expected behavior**
Clicking 'PPL Documentation' should lead to https://opensearch.org/docs/latest/observability/ppl/index/

**OpenSearch Version**
1.2.0

**Dashboards Version**
1.2.0

opensearch-project/OpenSearch-Dashboards#592

**Comment by joshuali925** [comment]
thanks for reporting this, the fix is merged to main and will be available in next release
