### ISSUE TITLE
Ensure backwards compatibility with ODFE

### ISSUE THREAD

**Issue by dblock** [opensearch-project/sql#36]
Coming from [opensearch-plugins#12](https://github.com/opensearch-project/opensearch-plugins/issues/12), enable upgrade to OpenSearch, while supporting backward compatibility.

- [x] Rename Namespaces (e.g. `com.amazon.opendistroforelasticsearch` to `org.opensearch`)
- [x] Rename Classes, Methods, Variables 
- [x] Rename Remaining Identifiers (e.g. `Opendistro` to `OpenSearch`).
- [x] Rename, and Backwards Compatibility for Rest APIs
- [x] Rename, and Backwards Compatibility for Settings 
- [x] Rename, and Backwards Compatibility for Indices
- [ ] Run in a backwards compatible way on top of OpenSearch 1.0 that has joined an ES 7.10.x cluster 
- [ ] Run in a backwards compatible way on top of OpenSearch 1.0 that has joined an ODFE 1.13.x cluster 
- [ ] Drop in replacement for the Opendistro version 1.13 of the plugin

**Comment by dai-chen** [comment]
@dblock Are the last 3 items (Run in a backwards compatible way... and Drop in replacement ...) still in the scope?

**Comment by dblock** [comment]
> @dblock Are the last 3 items (Run in a backwards compatible way... and Drop in replacement ...) still in the scope?

I am working on a backward compatibility FAQ. So far this is what this means:

_Upgrading your cluster from ElasticSearch to OpenSearch and OpenSearch Dashboards is just like upgrading your cluster between versions of ElasticSearch and Kibana. Specifically, OpenSearch supports rolling upgrades and restart upgrades from ElasticSearch 6.8.0 through ElasticSearch 7.10.2 and to OpenSearch 1.0. OpenSearch Dashboards supports restart upgrades from Kibana 6.8.0 through Kibana 7.10.2 and to OpenSearch Dashboards 1.0._

**Comment by dai-chen** [comment]
> > @dblock Are the last 3 items (Run in a backwards compatible way... and Drop in replacement ...) still in the scope?
> 
> I am working on a backward compatibility FAQ. So far this is what this means:
> 
> _Upgrading your cluster from ElasticSearch to OpenSearch and OpenSearch Dashboards is just like upgrading your cluster between versions of ElasticSearch and Kibana. Specifically, OpenSearch supports rolling upgrades and restart upgrades from ElasticSearch 6.8.0 through ElasticSearch 7.10.2 and to OpenSearch 1.0. OpenSearch Dashboards supports restart upgrades from Kibana 6.8.0 through Kibana 7.10.2 and to OpenSearch Dashboards 1.0._

Okay. So what's the action item for plugin owners here?

**Comment by dblock** [comment]
> > > @dblock Are the last 3 items (Run in a backwards compatible way... and Drop in replacement ...) still in the scope?
> > 
> > 
> > I am working on a backward compatibility FAQ. So far this is what this means:
> > _Upgrading your cluster from ElasticSearch to OpenSearch and OpenSearch Dashboards is just like upgrading your cluster between versions of ElasticSearch and Kibana. Specifically, OpenSearch supports rolling upgrades and restart upgrades from ElasticSearch 6.8.0 through ElasticSearch 7.10.2 and to OpenSearch 1.0. OpenSearch Dashboards supports restart upgrades from Kibana 6.8.0 through Kibana 7.10.2 and to OpenSearch Dashboards 1.0._
> 
> Okay. So what's the action item for plugin owners here?

I believe it's to fix any bugs that are in the way of that once we have compatibility testing enabled. If you think all the code for this is in, close the issue.

**Comment by dai-chen** [comment]
> > > > @dblock Are the last 3 items (Run in a backwards compatible way... and Drop in replacement ...) still in the scope?
> > > 
> > > 
> > > I am working on a backward compatibility FAQ. So far this is what this means:
> > > _Upgrading your cluster from ElasticSearch to OpenSearch and OpenSearch Dashboards is just like upgrading your cluster between versions of ElasticSearch and Kibana. Specifically, OpenSearch supports rolling upgrades and restart upgrades from ElasticSearch 6.8.0 through ElasticSearch 7.10.2 and to OpenSearch 1.0. OpenSearch Dashboards supports restart upgrades from Kibana 6.8.0 through Kibana 7.10.2 and to OpenSearch Dashboards 1.0._
> > 
> > 
> > Okay. So what's the action item for plugin owners here?
> 
> I believe it's to fix any bugs that are in the way of that once we have compatibility testing enabled. If you think all the code for this is in, close the issue.

Sure, will close once the last piece https://github.com/opensearch-project/sql/pull/82 merged. Thanks!
