### ISSUE TITLE
OCI Object Storage Repository

### ISSUE THREAD

**Issue by samuel-oci** [opensearch-project/sql#361]
**Is your feature request related to a problem? Please describe.**
Currently the existing blob store repositories do not support OCI object storage.

**Describe the solution you'd like**
We have developed an OCI native plugin for object storage that is convenient to use on the OCI platform.

For example you can configure the below repository and take advantage of instance principal authentication without the need to push credentials explicitly into a secret store. Can also force bucket creation if the bucket is missing.

```
curl -XPUT "https://localhost:9200/_snapshot/oci_repository" -H 'Content-Type: application/json' -d"
{
  \"type\": \"oci\",
  \"settings\": {
    \"client\": \"default\",
    \"endpoint\": \"https://objectstorage.${OCI_REGION}.oraclecloud.com\",
    \"bucket\": \"${OCI_BUCKET}\",
    \"namespace\": \"${NAMESPACE}\",
    \"bucket_compartment_id\": \"${OCI_BUCKET_COMPARTMENT}\",
    \"useInstancePrincipal\": true,
    \"forceBucketCreation\" : true
  }
}
" -u <user>:<password> --insecure
```

**Comment by stockholmux** [comment]
That's awesome @samuel-oci! It looks like this is similar to something like the [repository-azure built-in plugin](https://github.com/opensearch-project/OpenSearch/tree/20692a2ff2c512c1f858d4e4061dadc1d47ca378/plugins/repository-azure) but for OCI?

If so, I think this should probably be moved into [opensearch-project/OpenSearch](https://github.com/opensearch-project/OpenSearch/) as a proposal.

**Comment by samuel-oci** [comment]
Hi @stockholmux thank you for the response,
Apparently I forgot to add some context from my earlier [post](https://discuss.opendistrocommunity.dev/t/oci-object-storage-repository-plugin/8191). We actually already have the plugin ready as a standalone plugin and would like to contribute it, the question though is whether we should create a new repository for it like we do with other plugins.

There is also a preference from our side to contribute initially in a separate repo since we run into some difficulties to incorporate directly as part of the OpenSearch repo. So perhaps we can start with that and later consolidate with OpenSearch repo or any other that the community finds appropriate?

Thanks in advance,
Sam.

**Comment by samuel-oci** [comment]
following @stockholmux suggestion, opened the issue at:
https://github.com/opensearch-project/OpenSearch/issues/1854#issue-1094858841
and can probably close it here.
