### ISSUE TITLE
[BUG] opensearch-sql-cli is not on PyPi

### ISSUE THREAD

**Issue by automartin5000** [opensearch-project/sql#374]
**Describe the bug**
Can't install the sql-cli from PyPi because [it's not there (shows 404) 
](https://pypi.org/project/opensearch-sql-cli/)

**To Reproduce**
1. Try `pip3 install opensearch-sql-cli` per [instructions](https://opensearch.org/docs/latest/search-plugins/sql/cli/) and it's not found
2. Check [PyPi](https://pypi.org/project/opensearch-sql-cli/) to see if it's there and get a 404

Or for query issues:
1. Create the index with test documents by 'POST ...'
2. Run the query 'SELECT ...'
3. See error

**Expected behavior**
opensearch-sql-cli is in PyPi

**Comment by Alvaro360** [comment]
Hi, You do not need it to be able to run it. If you run directly  opensearchsql https://localhost:9200 --username admin --password admin with opensearch up, it works.

**Comment by zhongnansu** [comment]
cli has been released to Pypi
https://pypi.org/project/opensearchsql/ @automartin5000
