### ISSUE TITLE
Move opensearch-sql-cli to its own repository

### ISSUE THREAD

**Issue by hashworks** [opensearch-project/sql#389]
opensearch-sql-cli has a versioning scheme independent of the OpenSearch and OpenSearch Dashboards SQL plugins. However, there are no git tags created for those versions since those reference the version of the plugins. Additionally, its build process is completely independent as well.

Therefore, I think it would be best to move it to its own repository with its own git tags, issue tracker and pull requests.

For me this is an issue since I want to package it for Arch Linux but have no way to track new releases (f.e. GitHub Tag RSS).

**Comment by zhongnansu** [comment]
We'll cut specific tag for each `sql-cli` release once it's available on Pypi. Currently the initial `1.0.0` release is still ongoing. We'll discuss the proposal of making its own repo, but for 1.0 launch, it's not likely to happen.
