### ISSUE TITLE
[BUG] Can't execute Match full text query

### ISSUE THREAD

**Issue by Alvaro360** [opensearch-project/sql#397]
Hello!
I have the following problem.. The opensearch documentation says that I can execute the MATCH statement, but if I try to execute it, it says that the AGAINST statement is missing. If I add the AGAINST statement I get the following error
![image](https://user-images.githubusercontent.com/71035230/151145459-5342b33c-9c1a-4f40-806e-49b6c2da7bd1.png)

Could you please explain me what is the problem here?
Thanks.

**Comment by penghuo** [comment]
Could you try this? https://github.com/opensearch-project/sql/blob/main/docs/user/dql/functions.rst#match.
Let me know if you still have problem.

**Comment by Yury-Fridlyand** [comment]
Hi @Alvaro360,
`MATCH ... AGAINST ...` clause in MySQL allows you to make a full-text search. OpenSearch has much more powerful full-text search engine, it has few flexible functions to perform relevance based (full-text) search.
You can read docs about [full-text search DSL](https://opensearch.org/docs/latest/search-plugins/sql/sql-full-text/), it implementation in SQL plugin [on the OpenSearch website](https://opensearch.org/docs/latest/opensearch/query-dsl/full-text/) [1] and in the [repository](https://github.com/opensearch-project/sql/blob/main/docs/user/dql/functions.rst#relevance).

MySQL's `MATCH ... AGAINST ...` function is implemented by `MATCH` function in OpenSearch SQL plugin. Please, refer to the documentation, to PR #184 where it was implemented and issue #182 where it was described.

[1] SQL plugin documentation on the website is being updated right now

**Comment by dai-chen** [comment]
Closing. Feel free to reopen if anything else. Thanks!
