### ISSUE TITLE
Build and push SQL JDBC driver to Maven Central

### ISSUE THREAD

**Issue by delassiter** [opensearch-project/sql#401]
**Is your feature request related to a problem? Please describe.**
As with the now deprecated opendistro version of the SQL JDBC driver, we would wish to use the opensearch SQL JDBC driver in our project. Unfortunately we were not able to find a version on Maven Central and now need to build and manage the JAR ourselves.

**Describe the solution you'd like**
Have a build pipeline that builds the SQL JDBC driver and pushes it to Maven Central, whenever a new release occurs.

**Describe alternatives you've considered**
Building and the driver ourselves internally is an option, though comes with multiple disadvantages (e.g. keeping driver up to date and secure).

**Additional context**
N/A

Thank you for your hard work. If I can be of any assistance, please let me know.

**Comment by Yury-Fridlyand** [comment]
The release is tracked in https://github.com/opensearch-project/opensearch-build/issues/2692. I'm closing this ticket to avoid duplicates, and I'll notify you when JDBC driver released.
