### ISSUE TITLE
[Enhancement] Support full text search in new query engine.

### ISSUE THREAD

**Issue by penghuo** [opensearch-project/sql#421]
**Is your feature request related to a problem? Please describe.**
Legacy engine and new engine behavior is not compatible. For example, the following query use QUERY function which is only support in legacy engine. Legacy will return 200 records and it is not configured.
```
SELECT * 
FROM opensearch_dashboards_sample_data_flights 
WHERE DestAirportID='SYD' AND QUERY('Cancelled:false')
``` 
In new engine, there is a setting [plugins.query.size_limit](https://github.com/opensearch-project/sql/blob/main/docs/user/admin/settings.rst#plugins-query-size-limit) which could be used to control return size.

**Describe the solution you'd like**
Support [full text search functions](https://github.com/opensearch-project/sql/blob/main/docs/user/beyond/fulltext.rst) are implemented in legacy query engine. 

**Describe alternatives you've considered**
Support [plugins.query.size_limit](https://github.com/opensearch-project/sql/blob/main/docs/user/admin/settings.rst#plugins-query-size-limit) in legacy engine. 

**Additional context**

**Comment by penghuo** [comment]
We should also clarify the difference between https://github.com/opensearch-project/sql/blob/main/docs/user/admin/settings.rst#plugins-query-size-limit and LIMIT clause

**Comment by dai-chen** [comment]
Full support is already added to SQL engine v2 in https://github.com/opensearch-project/sql/issues/182
