### ISSUE TITLE
Incremented version to 1.2.5 

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/sql#435]
Incremented version to 1.2.5 in 1.2 following from https://github.com/opensearch-project/opensearch-build/issues/1600 to prepare for the next possible release.

Backport the change to higher version branches

**Comment by dai-chen** [comment]
1.2 branch is still on 1.2.4: https://github.com/opensearch-project/sql/blob/1.2/build.gradle#L29

**Comment by derek-ho** [comment]
Closing as released
