### ISSUE TITLE
[BUG] SQL requests doesn't work with otel-v1-apm-span-* indexes

### ISSUE THREAD

**Issue by enp** [opensearch-project/sql#438]
Tried to use SQL to requests otel-v1-apm-span-* indexes created by Data-Prepper from OTEL source, but even simple request ```select * from otel-v1-apm-span-000001``` returns ```Otel-v1-apm-span-000001: [IllegalStateException] There was internal problem at backend, this query is not runnable```

Problem is not described in https://opensearch.org/docs/latest/search-plugins/sql/troubleshoot/, so this is bug in docs at least or maybe elsewhere, right? Btw, are any requirements for index exists to support SQL requests?

**Comment by joshuali925** [comment]
Hi, the reason is that SQL/PPL did not support date_nanos data type. This will be supported in the coming release (1.3) as #360 is merged.

**Comment by dai-chen** [comment]
Closing as the PR is already merged.
