### ISSUE TITLE
opensearch_sql_odbc.taco references in md are missing

### ISSUE THREAD

**Issue by warrenjmcdonald** [opensearch-project/sql#439]
Trying to use the embedded link in the ODBC configuration guide  for the Tableau connector results in a 404.

Is there a new link available to this file? 
Could the md be updated to remove bad references.

**Comment by Yury-Fridlyand** [comment]
Unfortunately, this readme block is outdated.
There is [Tableau JDBC connector](https://github.com/opensearch-project/sql/tree/main/bi-connectors/TableauConnector). You can download the compiled connector from the [GitHub Actions workflow](https://github.com/opensearch-project/sql/actions/runs/2204957496).

**Comment by Yury-Fridlyand** [comment]
Fixed by #665.
