### ISSUE TITLE
[Enhancement] Support DATE_FORMAT(date,"%Y-%m-%dT%TZ") 

### ISSUE THREAD

**Issue by penghuo** [opensearch-project/sql#441]
**Is your feature request related to a problem? Please describe.**
OSQL DATE_FORMAT should support ISO 8601 Basic Format. 
`SELECT DATE_FORMAT("2022-02-21", "%Y-%m-%dT%TZ")`

**Describe the solution you'd like**
Support `SELECT DATE_FORMAT("2022-02-21", "%Y-%m-%dT%TZ")`

**Describe alternatives you've considered**
N/A

**Comment by vamsi-amazon** [comment]
Resolved as part of https://github.com/opensearch-project/sql/pull/460
