### ISSUE TITLE
[BUG] SemanticCheckException with field starting with a character

### ISSUE THREAD

**Issue by jerome-leanspace** [opensearch-project/sql#450]
**Describe the bug**
This happens when the field is not present.
1. When querying a field from an aliased index, a `SemanticCheckException` is thrown if the field starts with a letter but not if it starts with a number.
2. I found out that adding escaped quotes to the field will prevent it but this is incompatible with aliases.

**To Reproduce**
1.
Sample query with a character:
`SELECT telemetry.c1aeb711_3903_40f5_a8c4_ba505bae9db2_field FROM telemetry* AS telemetry  LIMIT 1`

```
{
  "error": {
    "reason": "Invalid SQL query",
    "details": "can't resolve Symbol(namespace=FIELD_NAME, name=c1aeb711_3903_40f5_a8c4_ba505bae9db2_field) in type env",
    "type": "SemanticCheckException"
  },
  "status": 400
}
```

Sample query with a number:
`SELECT telemetry.11aeb711_3903_40f5_a8c4_ba505bae9db2_field FROM telemetry* AS telemetry LIMIT 1`

Sample response:
```
{
  "schema": [{
    "name": "11aeb711_3903_40f5_a8c4_ba505bae9db2_field",
    "type": "object"
  }],
  "total": 10000,
  "datarows": [[null]],
  "size": 1,
  "status": 200
}
```

2.
Sample query with quotes:
`SELECT telemetry.\"c1aeb711_3903_40f5_a8c4_ba505bae9db2_field\" field FROM telemetry* AS telemetry  LIMIT 1`

Sample response:
```
{
  "error": {
    "reason": "Invalid SQL query",
    "details": "Illegal SQL expression : SELECT telemetry.\"c1aeb711_3903_40f5_a8c4_ba505bae9db2_field\" field FROM telemetry* AS telemetry  LIMIT 1",
    "type": "ParserException"
  },
  "status": 400
}
```

Sample query without quotes:
`SELECT telemetry.11aeb711_3903_40f5_a8c4_ba505bae9db2_field field FROM telemetry* AS telemetry  LIMIT 1`

Sample answer:
```
{
  "schema": [{
    "name": "11aeb711_3903_40f5_a8c4_ba505bae9db2_field",
    "alias": "field",
    "type": "object"
  }],
  "total": 10000,
  "datarows": [[null]],
  "size": 1,
  "status": 200
}
```

**Expected behavior**
The same behaviour for both, either throw an error or return the result. Adding quotes on the field should work with aliases.

**Host/Environment:**
 - OS: AWS
 - Version OpenSearch 1.1

**Comment by jerome-leanspace** [comment]
So `telemetry*` does not include anymore `c1aeb711_3903_40f5_a8c4_ba505bae9db2_field` nor does it include `11aeb711_3903_40f5_a8c4_ba505bae9db2_field`. And was never put manually in the mappings.
Some documents contained the first field, some contained the second one but they were deleted. Now when I query them I get this different behaviour.

**Comment by dai-chen** [comment]
Closing for now. Please reopen if you can provide more info of your index mapping. Thanks!
