### ISSUE TITLE
Update github action on building dependency ml-commons

### ISSUE THREAD

**Issue by jackiehanyang** [opensearch-project/sql#454]
**Is your feature request related to a problem? Please describe.**
Currently, since ml-commons artifact hasn't been published to public Maven, we add it into github action to build ml-commons. After ml-commons artifact is on public Maven, remove this github action and grab it from public Maven.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by penghuo** [comment]
#407

**Comment by jackiehanyang** [comment]
ml-commons has been published to remote maven https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/
