### ISSUE TITLE
Standardize file locations for supporting files 

### ISSUE THREAD

**Issue by sean-zheng-amazon** [opensearch-project/sql#482]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/127. 

We should standardize the file location across plugins by implementing following conventions:

- All supporting files for plugins should stay within the plugin's own folder: /plugins/my-plugin
- Within plugin's folder, we recommend following directory structure:
  - ./config: config files
  - ./bin: executables
  - ./lib: for plugins that use native libraries (e.g. libKNNIndexV2_0_11.so)
  - ./install: scripts called to bootstrap the plugin before first use.
  - ./docs: document files
  - ./certs: certificates for the security plugin
  - ./data: test/demo data
- All scripts should come in *nix and .bat flavors, should use OpenSearch's defaults for environment variables like $JAVA_HOME, so users can override these but don't need to specify them by default. Scripts should have 0755 permissions by default.

**Comment by dai-chen** [comment]
Checked SQL repo and only `docs` and `config` folder applies. Both are already in standard naming.
