### ISSUE TITLE
 Is there a "NOT MATCH_PHRASE" usage?

### ISSUE THREAD

**Issue by binbinjianjian** [opensearch-project/sql#488]
POST /_plugins/_sql?format=json
{
  "query": "SELECT * FROM log WHERE @timestamp BETWEEN '2022-01-29T00:30:00.000' AND '2022-01-29T09:00:00.000' AND MATCH_QUERY(level, 'ERROR') AND NOT MATCH_PHRASE(message,'Read timed out')"
}

I want to exclude the error log related phrases, but `NOT MATCH_PHRASE` does not take effect, find all the Read timed out log entries' Is there a problem with the spelling?

**Comment by dblock** [comment]
I moved this to the sql repo.

**Comment by penghuo** [comment]
@binbinjianjian Your spelling is correct, it is an issue. MATCH_PHRASE does work with NOT operator.

As a workaround, could you try QUERY. for example, `NOT QUERY(message,'\"Read timed out\"')"`

**Comment by MaxKsyunz** [comment]
Now that #185 is complete, SQL plugin supports `NOT MATCH_PHRASE`.
