### ISSUE TITLE
Replace checked-in ZIP with a dynamic dependency

### ISSUE THREAD

**Issue by dblock** [opensearch-project/sql#491]
Coming from https://github.com/opensearch-project/opensearch-build/issues/1750, replace checked-in ZIP with a dynamic dependency downloaded during bwc tests.

```
./sql/integ-test/src/test/resources/bwc/1.13.2.0/opendistro-sql-1.13.2.0.zip
```

**Comment by jackiehanyang** [comment]
Newly added ml-commons zip also needs to be replaced, tracking issue - https://github.com/opensearch-project/sql/issues/495

**Comment by dblock** [comment]
I'm (still) seeing

```
./sql/doctest/resources/ml-commons/opensearch-ml-2.0.0.0-SNAPSHOT.zip
```
