### ISSUE TITLE
Replace checked-in ml-commons ZIP with a dynamic dependency

### ISSUE THREAD

**Issue by jackiehanyang** [opensearch-project/sql#495]
**Describe the bug**
This [PR](https://github.com/opensearch-project/sql/pull/493) introduced a checked-in ml-commons zip file as dependency used for doc-test. Need to replace this with a dynamic dependency. See more in main issue [here](https://github.com/opensearch-project/sql/issues/491).

**Comment by dblock** [comment]
Reopening until https://github.com/opensearch-project/sql/pull/563 is merged.

**Comment by vamsi-amazon** [comment]
Closing since 563 is merged.
