### ISSUE TITLE
[FEATURE]  Bump the version for 1.3.2 opensearch-dashboards release

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/sql#544]
**Is your feature request related to a problem?**
Post Release activity https://github.com/opensearch-project/opensearch-build/issues/1885 - 

We need to bump the version for 1.3.2 in 1.x and 1.3 branches for 1.3.2 releases wrt to the release issue - https://github.com/opensearch-project/opensearch-build/issues/1882

ETA - 04/14/2022

**Comment by zelinh** [comment]
We should be able to close this issue as #593 is merged.
