### ISSUE TITLE
[BUG] Generated SQL query by tableau is incorrect for date operators

### ISSUE THREAD

**Issue by ghost** [opensearch-project/sql#553]
**What is the bug?**
Generated SQL query by tableau is incorrect for date operators

**How can one reproduce the bug?**
1. Run TDVT tests for:
   - exprtests/standard\setup.operator.date.txt
   - exprtests/standard\setup.date.B639952.txt
   - logicaltests/setup/staples\setup.BUGS.B8888.simple_lower.xml
2. See that they fail because the generated queries are not supported by OpenSearch.

**What is the expected behavior?**
These tests are expected to pass.

**Comment by dai-chen** [comment]
If possible, for this kind of issue, could you also post the TDVT queries and our error response? I think this would be easier to track and do a quick triage without looking into TDVT codebase. Thanks.

**Comment by guiangumpac** [comment]
> If possible, for this kind of issue, could you also post the TDVT queries and our error response? I think this would be easier to track and do a quick triage without looking into TDVT codebase. Thanks.

I apologize for the lack of detail. I have a fix in progress and will have a PR upstream in the next day or so. Will include more details moving forward. Thank you.

**Comment by dai-chen** [comment]
I assume this is already fixed. Please reopen if needed. Thanks!
