### ISSUE TITLE
[BUG] Generated SQL query by tableau is incorrect for casting string to int

### ISSUE THREAD

**Issue by ghost** [opensearch-project/sql#554]
**What is the bug?**
Generated SQL query by tableau is incorrect for casting string to int. OpenSearch does not support CAST("2.1" AS INT). Need to CAST(CAST("2.1" AS DOUBLE) AS INT)

**How can one reproduce the bug?**
1. Run TDVT test for exprtests/standard\setup.cast.int.nulls.txt
2. See that it fails.

**What is the expected behavior?**
This test should pass

**Comment by dai-chen** [comment]
I assume this is already fixed. Please reopen if needed. Thanks!
