### ISSUE TITLE
[BUG] Tableau Connector Casting Bool To String Fails

### ISSUE THREAD

**Issue by forestmvey** [opensearch-project/sql#571]
**What is the bug?**
Tableau connector casting bool to string fails.

**How can one reproduce the bug?**
1. Run tdvt.
2. Go to STR([bool0]) test case.
3. Notice test case uses true and false rather than 0 and 1.
4. See test fails.

**What is the expected behavior?**
Tableau expects 0 or 1.

**What is your host/environment?**
 - OpenSearch Server 1.3.1
 - Plugins: 2.0.0.0 JDBC Driver

**Do you have any additional context?**
Current query generated:
SELECT CAST((`calcs`.`bool0`) as string) AS `TEMP(Test)([3200082645](tel:3200082645))(0)`
FROM `calcs`
GROUP BY `TEMP(Test)([3200082645](tel:3200082645))(0)`

**Comment by dai-chen** [comment]
I see the PR added rewrite rule to TDVT dialect. I will close this issue and open a new one for reviewing if any such rewrite should be fixed in our engine. Thanks!
