### ISSUE TITLE
[BUG] [JDBC] Unable to execute the following query

### ISSUE THREAD

**Issue by neeltanAWS** [opensearch-project/sql#587]
**What is the bug?**
Following query throws an error from OpenSearch driver

`"SELECT totalNumberOfRegStatusSouryo, totalNumberOfStatusInUse, kpi, planName, totalNumberOfRegStatusTime, totalNumberOfService, planCode, timeStamp, totalNumberOfStatusStop, provider, totalNumberOfPacketControlInActive AS qoy7xkytwlidx5faegzhqzetxrvndq, totalNumberOfRegStatusDefault, totalNumberOfRegStatusTimerOn, totalNumberOfTurboOff, totalNumberOfTurboOn, pipeName, totalNumberOfCountfree, totalNumberOfPacketControlActive AS t3z99fh8qzoq956ejs44nevinye4s6\nFROM plan_statistics_information\nLIMIT 1000"`

Is this query malformed in any way? Why would it not return the 1000 rows as expected? 

**What is the expected behavior?**
Query executed successfully and gives us the rows back 

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by anirudha** [comment]
can you run this and post the error msg, and reopen the issue thanks
