### ISSUE TITLE
[2.0.0][Distribution]Remove rc1 qualifier reference in your code of 2.0 branch

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/sql#597]
We are coming from this issue: https://github.com/opensearch-project/opensearch-build/issues/2078 in your `2.0` branch.

### Note: This needs to be completed before `05/17` which is feature freeze day for `2.0.0-GA`.

1. If you have `OpenSearch plugin` in your repo, make sure your `build.gradle` remove `rc1` reference, leave as `""`.
```
opensearch_version = System.getProperty("opensearch.version", "2.0.0-SNAPSHOT")
buildVersionQualifier = System.getProperty("build.version_qualifier", "")
```

2. If you have `OpenSearch-Dashboards plugin` in your repo, make sure your `package.json` remove `rc1` reference, leave as `2.0.0.0`.
```
"version": "2.0.0.0",
```

3. If you have any `.github/workflows` contains hardcode `rc1` reference, please remove.

Thanks.

**Comment by vamsi-amazon** [comment]
Raised PR but pending on the build failure due to unavailability of ml-commons 2.0.0.0 version.
