### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by shivavemula1** [opensearch-project/sql#605]
Opensearch.mez  file not available. 
For power bi connector

**Comment by MaxKsyunz** [comment]
@shivavemula1 PowerBI ships with a version of the OpenSearch connector. [This](https://docs.microsoft.com/mt-MT/power-query/connectors/amazonopensearchservice) document explains how to use it.

Alternatively, you could use the MEZ from this [workflow](https://github.com/opensearch-project/sql/actions/runs/2277690525) following instructions from [here](https://github.com/opensearch-project/sql/blob/main/sql-odbc/docs/user/power_bi_support.md).

**Comment by dai-chen** [comment]
Closing. Feel free to reopen if anything else. Thanks!
