### ISSUE TITLE
Implement catalog functionality

### ISSUE THREAD

**Issue by vamsi-amazon** [opensearch-project/sql#619]
Requirements.

* Taking input configuration from user for each catalog.
* Configuration should cover all the required details to connect to the catalog instance.
* Securely store any confidential data mentioned in the configuration.

Solution Overview (Tech tasks)
<TODO>

**Comment by penghuo** [comment]
Question:
1. Is there any DML support for catalog? e.g. `CREATE CATALOG catalog`, `SHOW CATALOGS`. Does user could create catalog dynamically?
2. Does the `default` catalog mapping to the current OpenSearch cluster?
3. What auth type is support for CATALOG? Basic Auth? Access-Key/Id?

**Comment by vamsi-amazon** [comment]
Will include all of these into separate tasks.
