### ISSUE TITLE
Separate components that ship separately into their own repos

### ISSUE THREAD

**Issue by dblock** [opensearch-project/sql#640]
**Is your feature request related to a problem?**

Coming from https://github.com/opensearch-project/opensearch-build/issues/2188, it's not possible to release and tag the multiple components (`workbench`, `sql-odbc`, `sql-jdbc`, ...) that come out of this repo separately as, for example, `2.0.0`. This means we must release all these parts together, or nobody can ever locate the correct code using tags.

**What solution would you like?**
The plugins/drivers should live in their own repos.

**What alternatives have you considered?**
A tagging scheme such as opensearch-2.0.0 vs. opensearch-odbc-driver-2.0.0.

**Comment by dblock** [comment]
See https://github.com/opensearch-project/opensearch-build/issues/2188#issuecomment-1259874232 in which we decided to split front-end and back-end components. For the SQL plugin there are a lot more individual components. Those that ship separately should split, and those that ship at the same time as the SQL plugin, can stay. @anirudha what do you think we should keep/split?

**Comment by dai-chen** [comment]
@YANG-DB I assume you've worked on this. Please close this once done. Thanks!

**Comment by dai-chen** [comment]
+ https://github.com/opensearch-project/sql/issues/964
+ https://github.com/opensearch-project/sql/issues/965
+ https://github.com/opensearch-project/sql/issues/966

**Comment by YANG-DB** [comment]
New Repos generated from internal folder in SQL :

 - jdbc-sql ==> https://github.com/opensearch-project/sql-jdbc
 - odbc-sql ==> https://github.com/opensearch-project/sql-odbc
 - cli-sql ==> https://github.com/opensearch-project/sql-cli
 - dashboards-query-workbench ==> https://github.com/opensearch-project/dashboards-query-workbench

Main SQL repo remains the plugin container with focus on SQL / PPL engine
