### ISSUE TITLE
[FEATURE] `1.x` version increment process, remove dependency zips.

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/sql#673]
**Is your feature request related to a problem?**
The version increment PR's for `1.x` requires ml-commons zips to be part of `doctest/resources/ml-commons/` folder.
Sample PR: https://github.com/opensearch-project/sql/pull/593/files

**What solution would you like?**
Remove the injection of zip file via PR and use available `latest` URL to download the required zips
Example URL: https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.1/latest/linux/x64/builds/opensearch/plugins/opensearch-ml-1.3.1.0.zip
This is already the case of version increments for `2.x` the zips are not added as part of PR
Example `2.x` version increment PR : https://github.com/opensearch-project/sql/pull/637/files

**What alternatives have you considered?**
`https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/<version>/latest/linux/x64/builds/opensearch/plugins/<plugin name + version>.zip` where `<version>` and `plugin name` parameter can be injected using gradle properties.

**Do you have any additional context?**
Committing a zip via a PR limits the capabilities to perform auto increment PR, more details on https://github.com/opensearch-project/opensearch-build/issues/1375

**Comment by prudhvigodithi** [comment]
Hey @anirudha @joshuali925 can you take a look at this issue.
@bbarani

**Comment by prudhvigodithi** [comment]
Hey @joshuali925 and @anirudha can you please post an update on this, this is pending to close the associated [META issue](https://github.com/opensearch-project/opensearch-build/issues/1375).
Thank you

**Comment by bbarani** [comment]
@joshuali925 @anirudha Can you please prioritize this request? We need to remove the dependency of zips to automate the PR auto increment process. CC: @CEHENKLE @xinl

**Comment by prudhvigodithi** [comment]
Hey @joshuali925 and @anirudha assuming this can be closed, for last version increment 1.3.5 I dont see a ml-commons zip file checked in to version increment PR https://github.com/opensearch-project/sql/pull/766.
Thank you
