### ISSUE TITLE
[BUG] Explain does not show the DSL Query- Broken Feature

### ISSUE THREAD

**Issue by 007ramukakaji** [opensearch-project/sql#690]
On Any given sql query of opensearch, want to know the DSL query behind it.
when i use Explain to get the DSL, it shows very vague DSL

This DSL is not useful at all , if we want to apply must, must not, range filters, aggregation etc. Its not easy to go and define those
Its a broken feature from elastic.
If want to continue with a new DSL language what is the way to run a app with API with must, must not, range filters, aggregation feature in elegant way with API?

Do we have any examples?

**Comment by Yury-Fridlyand** [comment]
As it is said in https://github.com/opensearch-project/sql/issues/218

> the explain is no longer translated to OpenSearch DSL, but to the query planning within the new query engine instead.

**Comment by dai-chen** [comment]
@007ramukakaji Currently explain returns execution plan in readable format as Yury said. You can find DSL in OpenSearchIndexScan operator at lowest level. I'm closing this issue for now. Feel free to reopen if any other need. Thanks!
