### ISSUE TITLE
Implement OpenSearch core branching strategy

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/sql#692]
### Description

Ensure `MAJOR_VERSION.x` branch exists, the `main` branch acts as source of truth effectively working on 2 versions at the same time.

### Related META issue

https://github.com/opensearch-project/opensearch-plugins/issues/142

### Current Behavior

Currently plugins follow a branching strategy where they work on `main` for the next development iteration, effectively working on 2 versions at the same time. This is not always true for all plugins, the release branch or branch pattern is not consistent, the lack of this standardization would limit multiple automation workflows and alignment with core repo. More details on [META ISSUE](https://github.com/opensearch-project/opensearch-plugins/issues/142)

### Proposed solution

Follow OpenSearch [core branching](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#opensearch-branching). Create `1.x` and `2.x` branches, do not create `2.0` as a branch of main, instead create `main -> 2.x -> 2.0`. Maintain working CI for 3 releases at any given time.

**Comment by prudhvigodithi** [comment]
Hey @ps48 can you please post an update and make the necessary changes to align with core branching strategy.
Thank you
@dblock @bbarani @CEHENKLE

**Comment by ps48** [comment]
@prudhvigodithi I'm currently aligning 1.x and 2.x branches. Do we have to update main to 3.0?

**Comment by ps48** [comment]
Updated 1.x and created 2.x from main. @prudhvigodithi please feel free to re-open the issue, if the main needs to be updated to 3.0

**Comment by ps48** [comment]
@prudhvigodithi waiting for ml-commons to merge in 3.0

**Comment by ps48** [comment]
Closed the PR for main branch, for now. Will reopen once we have decision https://github.com/opensearch-project/opensearch-plugins/issues/142. Let's keep this issue open.

**Comment by penghuo** [comment]
Try to upgrade main to 3.0 failed. https://github.com/opensearch-project/sql/pull/831.

```
 > Could not find org.apache.lucene:lucene-core:9.4.0-snapshot-ddf0d0a.
   Searched in the following locations:
     - file:/home/runner/.m2/repository/org/apache/lucene/lucene-core/9.4.0-snapshot-ddf0d0a/lucene-core-9.4.0-snapshot-ddf0d0a.pom
     - https://aws.oss.sonatype.org/content/repositories/snapshots/org/apache/lucene/lucene-core/9.4.0-snapshot-ddf0d0a/lucene-core-9.4.0-snapshot-ddf0d0a.pom
     - https://repo.maven.apache.org/maven2/org/apache/lucene/lucene-core/9.4.0-snapshot-ddf0d0a/lucene-core-9.4.0-snapshot-ddf0d0a.pom
```

**Comment by dblock** [comment]
The job-scheduler issue was fixed, see https://github.com/opensearch-project/job-scheduler/pull/242.

**Comment by penghuo** [comment]
* 2.x branch is ready.
* main branch is blocked. because of IT failed. https://github.com/opensearch-project/sql/actions/runs/3055823327/jobs/4929313950. Need investigate more, seems breaking change in core.

**Comment by dblock** [comment]
To close this issue:

- [ ] main is building 3.0
- [ ] 2.x is building next 2.x, which is currently 2.4.0
- [ ] 2.3 is building next 2.3, which is 2.3.1
- [ ] manifests in https://github.com/opensearch-project/opensearch-build/tree/main/manifests include all 3

**Comment by penghuo** [comment]
2.3.1. https://github.com/opensearch-project/sql/pull/894

**Comment by bbarani** [comment]
@penghuo Updating the tagged version for this issue to 2.4.0
