### ISSUE TITLE
[FEATURE] Proposal for Spring framework dependency maintenance

### ISSUE THREAD

**Issue by dai-chen** [opensearch-project/sql#741]
**Is your feature request related to a problem?**
Spring framework used in our plugin needs to be upgraded very often to solve CVE introduced.

**What solution would you like?**
Actually we only need very simple Dependency Inject mechanism. Other lightweight framework such as Guice may be sufficient and save maintenance trouble.

**What alternatives have you considered?**
Alternatively, we can extract Spring version to single place in root Gradle config. It would be easier to bump its version.

**Do you have any additional context?**
N/A

**Comment by dai-chen** [comment]
Related: https://github.com/opensearch-project/sql/issues/611

**Comment by anirudha** [comment]
+1 for guava
