### ISSUE TITLE
[BUG] Wrong URL for PPL documentation on Workbench

### ISSUE THREAD

**Issue by neyp** [opensearch-project/sql#749]
**Describe the bug**

Wrong URL for PPL documentation on Workbench.

**To Reproduce**
1. Go to Workbench
2. Click on 'PPL documentation'

**Expected behavior**
Load [the correct page](https://opensearch.org/docs/latest/observability-plugin/ppl/index/).

**OpenSearch Version**
1.3

**Dashboards Version**
AWS 1.3

**Comment by Yury-Fridlyand** [comment]
Note, PPL documentation location will be changed in https://github.com/opensearch-project/documentation-website/pull/830.

**Comment by joshuali925** [comment]
Thanks for letting us know, added a PR https://github.com/opensearch-project/sql/pull/758
