### ISSUE TITLE
[BUG] `score` cannot be used in field name

### ISSUE THREAD

**Issue by dai-chen** [opensearch-project/sql#788]
**What is the bug?**
Field with `score` is not supported and causing fallback to legacy query processing.

**How can one reproduce the bug?**
N/A (Fallback will occur as if the query is handled properly. However if any new feature in v2 used, the legacy code throws exception)

**What is the expected behavior?**
`score` can be present in index or field name.

**What is your host/environment?**
 - OS: OpenSearch 2.2
 - Plugins: SQL

**Do you have any screenshots?**
N/A

**Do you have any additional context?**
Code related: https://github.com/opensearch-project/sql/blob/main/sql/src/main/antlr/OpenSearchSQLIdentifierParser.g4#L60

**Comment by acarbonetto** [comment]
@dai-chen This can be closed as part of https://github.com/opensearch-project/sql/pull/1456.
