### ISSUE TITLE
[FEATURE] Support `grok` command in PPL

### ISSUE THREAD

**Issue by joshuali925** [opensearch-project/sql#814]
**Is your feature request related to a problem?**
PPL currently supports `parse` command that allows user to extract text from a field with regex pattern. But regex is difficult to write while many extracted patterns are likely to be existing patterns. Supporting `grok` can make this easier.

**What solution would you like?**
Allow extracting text using [java-grok](https://github.com/thekrakken/java-grok) similar to current `parse` command.

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by penghuo** [comment]
I think we could add `grok` as a method in `parse` command. 
1. I feel adding a lots of command will confuse customer.
2. If customer require `grok` command in future, we could add it later, there is no one way door.
