### ISSUE TITLE
[FEATURE] Support extracting log patterns using PPL

### ISSUE THREAD

**Issue by joshuali925** [opensearch-project/sql#815]
**Is your feature request related to a problem?**
It would be helpful to group similar log lines together, and observe changes happening to different groups of logs, instead of focusing directly on each log line. This can be done by extracting log patterns from each log line. Also see https://github.com/opensearch-project/observability/issues/893.

**What solution would you like?**
Add a command in PPL that lets users extract patterns from a given field.

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by penghuo** [comment]
As we discussed, could we add a method as `parse method=punt` in parse command.
