### ISSUE TITLE
Power BI throws error after importing data from Opensearch using Opensearch connector. 

### ISSUE THREAD

**Issue by donnergid** [opensearch-project/sql#818]
**Is your feature request related to a problem?**
A clear and concise description of what the problem is, e.g. _I'm always frustrated when [...]_

After adding sample flight data to the Opensearch cluster, imported the same data into Power BI using the Opensearch Service (BETA) connector and a Direct Query. The data throws and error in the ODBC connector when adding to a visual. 

Repro steps: 
- Create Opensearch cluster with ElasticSearch 7.10. 
- Import sample flight data included with the install. 
- Open Power BI and Get Data
- Browse to the the Amazon OpenSearch Service (Beta) option and connect 
- Input endpoint, port and enable SSL, choose DirectQuery for Data connectivity mode
- Input username/password. 
- Choose the sample flight data and load the data. 
- Create a PIE chart visualization
- Add DestCityName and DestCountry items to the visualization. 
- Observe the error message. 

Error:
OLE DB or ODBC error: [DataSource.Error] ODBC: ERROR [42000] [OpenSearch][SQL ODBC Driver][SQL Plugin] There was internal problem at backend: No type found for field:"

**What solution would you like?**
Expect to be able to add visualizations without error.

**Comment by Yury-Fridlyand** [comment]
@donnergid,

Could you, please, clarify what is the first step? Is it an upgrade from ODFE?
Which ODBC driver do you use?

Screenshots from PowerBI are appreciated too.

**Comment by donnergid** [comment]
[opensearch-sql-odbc-win32-1.4.0.0.msi](https://artifacts.opensearch.org/opensearch-clients/odbc/opensearch-sql-odbc-win32-1.4.0.0.msi)

**Comment by donnergid** [comment]
Importing sample data into Power BI with Direct Query was the first step.

**Comment by Yury-Fridlyand** [comment]
@donnergid,

Could you clarify this please?

> Create Opensearch cluster with ElasticSearch 7.10.

Is it an upgrade from ODFE?

**Comment by donnergid** [comment]
Sorry, no upgrade. Just a fresh install using ES 7.10 (reproduction of a customer environment).

**Comment by Yury-Fridlyand** [comment]
The PowerBI connector uses OpenSearch ODBC driver which is incompatible with ES. Sorry, I don't understand how it works.

**Comment by dai-chen** [comment]
@donnergid I'm closing this issue due to insufficient info for further investigation. Feel free to reopen as needed. Thanks!
