### ISSUE TITLE
[BUG] Non-anonymized queries can be added to OpenSearch logs

### ISSUE THREAD

**Issue by MaxKsyunz** [opensearch-project/sql#821]
`QueryDataAnonymizer` fails to anonymize queries that are  only supported by the v2 engine.

When that happens, the query including parameter values is added to OpenSearch log.

### Root Cause

`QueryDataAnonymizer` uses v1 parser to determine what elements in the AST need to be anonymized. When a query fails v1 engine, anonymization is skipped and the query is logged as-is.

**Comment by MaxKsyunz** [comment]
Relates to #787

**Comment by Yury-Fridlyand** [comment]
Completed via #1665
