### ISSUE TITLE
[FEATURE] A Universal ML command in PPL for train/predict/trainandpredict

### ISSUE THREAD

**Issue by jngz-es** [opensearch-project/sql#849]
**Is your feature request related to a problem?**
Currently for each new algorithm in ml-commons, we have to add a new command in PPL which means we have to implement an entire PPL command process including syntax parser, logical plan and physical plan. It is very inefficient for development.
From user interface perspective, it is more clean and reasonable to have one command for all algorithms than each command for each algorithm.

**What solution would you like?**
We want to provide only one PPL command (ml) for all algorithms in ml-commons about train/predict/trainandpredict. So for new algorithm launch, we just need to add some changes in ml-commons part, don't need to touch PPL plugin part any more.

**What alternatives have you considered?**
We considered add 3 commands each for train, predict and trainandpredict in terms of ml-commons APIs.

**Do you have any additional context?**
We plan to keep the existing algorithms PPL commands at this moment, but want to deprecate them in the future.

**Example**
ml action=train algo=kmeans centroids=3 iterations=2 distance_type='cosine'

**Comment by dai-chen** [comment]
@jngz-es I've marked this as RFC. If needed, you can put some query examples for community feedback. Thanks!

**Comment by jngz-es** [comment]
> @jngz-es I've marked this as RFC. If needed, you can put some query examples for community feedback. Thanks!

Added an example query, thanks!

**Comment by dai-chen** [comment]
I assume we can close this. If anything else, please open new issue labeled with future release version. Thanks!
