### ISSUE TITLE
[FEATURE] Support session token in OpenSearch SQL CLI

### ISSUE THREAD

**Issue by penghuo** [opensearch-project/sql#854]
**Is your feature request related to a problem?**
Currently, OpenSearch SQL CLI only support access_key and secret_key. https://github.com/opensearch-project/sql/blob/main/sql-cli/src/opensearch_sql_cli/opensearch_connection.py#L61

**What solution would you like?**
OpenSearch SQL CLI should support session token. https://pypi.org/project/requests-aws4auth/

**Comment by anirudha** [comment]
this is a cli release, not part of the distribution
