### ISSUE TITLE
how can query on multiple indexes,like we do in sql join ( inner join,left join etc) using DSL in opensearch

### ISSUE THREAD

**Issue by Shivacharangoud** [opensearch-project/sql#893]
how can query on multiple indexes,like we do in sql join ( inner join,left join etc) using DSL in opensearch @anirudha @kyleconroy @spk @mattweber

**Comment by Shivacharangoud** [comment]
Answer this please

**Comment by Shivacharangoud** [comment]
Please answer this

**Comment by dai-chen** [comment]
@Shivacharangoud DSL query is part of OpenSearch core. AFAIK, there is no join support in DSL. You can take a look at parent-child field and nested field. These may be the only support in OpenSearch: https://opensearch.org/docs/latest/opensearch/supported-field-types/join/

**Comment by dai-chen** [comment]
I'm transferring this issue back to OpenSearch core repo. Because the ask was "I want to do the same using DSL, how can I do it."
