### ISSUE TITLE
[BUG] Incorrect versioning of JDBC Jar

### ISSUE THREAD

**Issue by normanj-bitquill** [opensearch-project/sql#903]
**What is the bug?**
The JDBC jar is always at version 1.1.0.1 (at least in the filename). I just checked [here](https://github.com/opensearch-project/sql/actions/runs/3047371080) and the Jar file still has 1.1.0.1 in the filename.

**How can one reproduce the bug?**
Check the filename of the JDBC jar file. It will have 1.1.0.1 in the name rather than the actual version.

**What is the expected behavior?**
Jar artifacts contain the proper version in the filename.

**What is your host/environment?**
N/A

**Do you have any screenshots?**
N/A

**Do you have any additional context?**
No

**Comment by MaxKsyunz** [comment]
@normanj-bitquill what version did you expect?

OpenSearch project tries to follow [semantic versioning](https://semver.org/). JDBC driver is fairly straight-forward and did not need to break backwards compatibility yet. It should be compatible with any version of OpenSearch available.

**Comment by normanj-bitquill** [comment]
I expect that the JDBC Driver follows standard versioning.
* The version increases with time
* Each version maps to one and only one commit in your repo

Every single build of the JDBC jar file that OpenSearch is producing has the version 1.1.0.1. If I download the jar today, it claims to be version 1.1.0.1. If it come back in a few months and download the latest, it will still claim to be 1.1.0.1.

There should be public releases of the OpenSearch JDBC jar. You should never have two releases with the same release number.

I can't think of how to make this clear. Just start versioning the OpenSearch JDBC Driver. Look at the OpenSearch project. It has releases 1.2, 2.0, 2.1, etc. Each one of those releases maps back to a tag in the repo.

This is what OpenSearch JDBC is doing:
Create version 1.1.0.1
Add a feature
Publish version 1.1.0.1
Fix a bug
Publish version 1.1.0.1

This is what almost every other software project does (including OpenSearch):
Create a version 1.1
Add a feature
Publish version 1.2
Fix a bug
Publish version 1.2.1

**Comment by acarbonetto** [comment]
@normanj-bitquill you are correct, but so far there has been no new features to the JDBC driver since 1.1.0.1. 
There are a couple of JDBC bug fixes, and once they go in, we can publish a new version of the JDBC drivers (probably: 2.0)

**Comment by joshuali925** [comment]
we only released 1.1.0.1 once, and JDBC didn't have any new releases since 1.1.0.1

If we are publishing a new release, it should be 1.2.0.0 unless there is a breaking change

**Comment by normanj-bitquill** [comment]
I see. I didn't realize that there had been no changes in a while. I'll close this issue.
