### ISSUE TITLE
[BUG] 2.x SQL integTest on Windows trying to find zip from `releases`

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/sql#928]
Getting the 2.4.0 windows zip from here:
https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.4.0/6230/windows/x64/zip/dist/opensearch/opensearch-2.4.0-windows-x64.zip

Run SQL integTest

```
* What went wrong:
Execution failed for task ':integ-test:integTest'.
> Could not resolve all files for configuration ':integ-test:opensearch_distro_extracted_testclusters-integ-test-integTest-0-2.4.0-'.
   > Could not resolve opensearch-distribution:opensearch:2.4.0.
     Required by:
         project :integ-test
      > Could not resolve opensearch-distribution:opensearch:2.4.0.
         > Could not get resource 'https://artifacts.opensearch.org/releases/core/opensearch/2.4.0/opensearch-min-2.4.0-windows-x64.zip'.
            > Could not HEAD 'https://artifacts.opensearch.org/releases/core/opensearch/2.4.0/opensearch-min-2.4.0-windows-x64.zip'. Received status code 403 from server: Forbidden
      > Could not resolve opensearch-distribution:opensearch:2.4.0.
         > Could not get resource 'https://artifacts.opensearch.org/release-candidates/core/opensearch/2.4.0/opensearch-min-2.4.0-windows-x64.zip'.
            > Could not HEAD 'https://artifacts.opensearch.org/release-candidates/core/opensearch/2.4.0/opensearch-min-2.4.0-windows-x64.zip'. Received status code 403 from server: Forbidden

```

We should get the artifacts from 
```
https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/<VERSION>/latest/linux/x64/tar/builds/opensearch/dist/opensearch-min-<VERSION>-windows-x64.zip
```

Thanks.

**Comment by MaxKsyunz** [comment]
@peterzhuamazon should this issue be moved to OpenSearch repo?

These artifacts are provided by [`DistributionDownloadPlugin`](https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/src/main/java/org/opensearch/gradle/DistributionDownloadPlugin.java) from OpenSearch. [This](https://github.com/opensearch-project/OpenSearch/blob/eb3301554ec7e1a07866508ffc390b8651dc3394/buildSrc/src/main/java/org/opensearch/gradle/DistributionDownloadPlugin.java#L207) is where it references `artifacts.opensearch.org`

**Comment by dblock** [comment]
@prudhvigodithi does this need to be fixed in OpenSearch?

**Comment by derek-ho** [comment]
@peterzhuamazon where are you getting this from? I have disabled integration test for windows and macos for now... The changes were just merged in yesterday. Can you re-run from your side? I am pretty sure you shouldn't be seeing this...

**Comment by peterzhuamazon** [comment]
@derek-ho this is an 8-day issue opened when it first started.
Could you confirm it is fixed now then you can close the issue.

Thanks.

**Comment by derek-ho** [comment]
Closing as CI is passing now on windows after disabling those sections
