### ISSUE TITLE
[FEATURE] Move Opensearch Related functions out of the CORE layer.

### ISSUE THREAD

**Issue by vamsi-amazon** [opensearch-project/sql#930]
**Is your feature request related to a problem?**
Currently Opensearch match functions are written in core layer and exposed to all kinds of catalogs. The ask from this issue to move these opensearch specific functions to opensearch connector and expose it via StorageEngine Interface.

**What solution would you like?**

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by dai-chen** [comment]
Duplicate as https://github.com/opensearch-project/sql/issues/811. Closing to track in one place. Thanks!
