### ISSUE TITLE
[FEATURE] Change trigger when `functionRepository` created

### ISSUE THREAD

**Issue by Yury-Fridlyand** [opensearch-project/sql#944]
## Is your feature request related to a problem?
`functionRepository` created on execution of the each query. For the first query on the current server run this creates a significant lag in ~3-5 seconds regardless of query complexity. The delay grows along with amount of functions implemented.

## What solution would you like?
N/A

## What alternatives have you considered?
N/A

## Do you have any additional context?
The task is to define another trigger when SQL plugin should build the repository.
* Do it once
* Decide when to do
  * on init?
  * in background after init?
* When and how to re-init a repository (consider a new function repository added/updated in runtime)

**Comment by dai-chen** [comment]
It may be helpful that we avoided creating Spring container per request in https://github.com/opensearch-project/sql/pull/822. On the safe side, it was merged to maximus-m1 feature branch. If no issue, it will be merged to 2.x in future. Thanks!

**Comment by dai-chen** [comment]
Changes in https://github.com/opensearch-project/sql/pull/822 is already merged to main and 2.x branch. Thanks!
