### ISSUE TITLE
Split CLI Tool into it's own repository

### ISSUE THREAD

**Issue by acarbonetto** [opensearch-project/sql#966]
### Is your feature request related to a problem? Please describe

As mentioned under https://github.com/opensearch-project/opensearch-build/issues/2188, the CLI tool is deployed alongside the SQL plugin in the SQL plugin repo. However, the UI tool should follow its own CI/CD process and release versioning instead of depending on the SQL plugin. These are separate release artefacts and they should have their own separate repository project.

### Describe the solution you'd like

Move SQL-CLI folder into it's own project repository under the OpenSearch project.

### Describe alternatives you've considered

Alternatives (such as the status quo) means that repositories will be responsible for multiple release artefacts, which is less ideal.

### Additional context

Additional discussion under: https://github.com/opensearch-project/opensearch-build/issues/2188 including Pro/Cons

**Comment by dai-chen** [comment]
New repo: https://github.com/opensearch-project/sql-cli
