### ISSUE TITLE
[FEATURE] Support Prometheus Catalog Integ Tests for mac/windows.

### ISSUE THREAD

**Issue by vamsi-amazon** [opensearch-project/sql#982]
**Is your feature request related to a problem?**
In the current state, prometheus integration tests work only on linux systems as we are only downloading and running the binary for linux.

**What solution would you like?**
Need to figure out the OS type and download the relevant prometheus binary to use.

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by penghuo** [comment]
It is a blocker for macOS local integ test now.

**Comment by vamsi-amazon** [comment]
https://github.com/opensearch-project/sql/pull/1069
Resolved in this PR.
